<?php

/**
 * @file
 * Contains az_metrics.module.
 */

use Drupal\Component\Serialization\Json;

const AZ_METRICS_URL = 'https://api.web.arizona.edu/v1';

/**
 * Get all data needed for reporting.
 */
function az_metrics_data() {
  $domains = \Drupal::database()
    ->query('SELECT * FROM {az_metrics_domains}')
    ->fetchAll();

  $data = [
    'domains' => array_map(function ($x) { return $x->domain; }, $domains),
    'mail' => \Drupal::config('system.site')->get('mail', ''),
    'name' => \Drupal::config('system.site')->get('name', ''),
    'uuid' => \Drupal::config('system.site')->get('uuid', ''),
  ];

  return $data;
}

/**
 * Implements hook_cron().
 */
function az_metrics_cron() {
  $data = az_metrics_data();

  \Drupal::httpClient()
            ->post(AZ_METRICS_URL . "/metrics", [
                'headers' =>  [
                                'X-Api-Key' => 'secret',
                                'Content-Type' => 'application/json'
                              ],
                'body' => Json::encode($data)
              ]);
}
