field_group.field_group_formatter_plugin.accordion:
  type: field_group.field_group_formatter_plugin.base
  label: 'Mapping for the accordion formatter settings'
  mapping:
    effect:
      type: string
      label: 'Effect on the accordion'

field_group.field_group_formatter_plugin.accordion_item:
  type: field_group.field_group_formatter_plugin.base
  label: 'Mapping for the accordion item formatter settings'
  mapping:
    formatter:
      type: string
      label: 'Formatting of the item'
    description:
      type: text
      label: 'Description of the item'
    required_fields:
      type: boolean
      label: 'Mark for required fields'
