/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(($, Drupal) => {
  Drupal.behaviors.azAlphabeticalListing = {
    attach() {
      $('#az-js-alpha-navigation li').each((index, element) => {
        const groupId = $(element).children().attr('data-href');
        if ($(groupId).length !== 0) {
          $(element).removeClass('disabled');
          $(element).children().attr('tabindex', '0').attr('aria-hidden', 'false').attr('href', groupId);
        } else {
          $(element).addClass('disabled');
          $(element).children().attr('tabindex', '-1').attr('aria-hidden', 'true').removeAttr('href');
        }
      });
      function azAlphabeticalListingCheckNoResults() {
        let visibleResults = false;
        $('.az-alphabetical-listing-group-title').each((index, element) => {
          if (!$(element).hasClass('hide-result')) {
            visibleResults = true;
          }
        });
        if (!visibleResults) {
          $('#az-js-alphabetical-listing-no-results').show();
        } else {
          $('#az-js-alphabetical-listing-no-results').hide();
        }
      }
      function azAlphabeticalListingGroupLoop() {
        $('.az-alphabetical-listing-group-title').each((index, element) => {
          const elementId = $(element).attr('id');
          const group = elementId.toLowerCase();
          const targetGroup = `.az-alphabetical-letter-group-${group}`;
          let visibleChildren = false;
          $(targetGroup).each((resultIndex, resultElement) => {
            if (!$(resultElement).hasClass('hide-result')) {
              visibleChildren = true;
            }
          });
          const navTarget = $('#az-js-alpha-navigation').find(`.page-link[data-href='#${elementId}']`);
          if (!visibleChildren) {
            $(element).hide();
            $(element).addClass('hide-result');
            navTarget.parent().addClass('disabled');
            navTarget.attr('tabindex', '-1').attr('aria-hidden', 'true').removeAttr('href');
          } else {
            $(element).show();
            $(element).removeClass('hide-result');
            navTarget.parent().removeClass('disabled');
            navTarget.attr('tabindex', '0').attr('aria-hidden', 'false').attr('href', $(element).attr('id'));
          }
        });
      }
      $('#az-js-alphabetical-listing-search').keyup(event => {
        const filter = $(event.currentTarget).val();
        $('.az-js-alphabetical-listing-search-result').each((index, element) => {
          const searchResultText = $(element).find('.az-alphabetical-listing-item').text();
          if (searchResultText.search(new RegExp(filter, 'i')) < 0) {
            $(element).find('az-alphabetical-listing-item').attr('tabindex', '0');
            $(element).addClass('hide-result');
            $(element).hide();
          } else {
            $(element).find('.az-alphabetical-listing-item').attr('tabindex', '0');
            $(element).removeClass('hide-result');
            $(element).show();
          }
        });
        azAlphabeticalListingGroupLoop();
        azAlphabeticalListingCheckNoResults();
      });
      const $root = $('html, body');
      const breakpoint = 600;
      $('#az-js-alpha-navigation a').on('click', event => {
        event.preventDefault();
        const $alphaNav = $('#az-js-floating-alpha-nav-container');
        const href = $.attr(event.currentTarget, 'data-href');
        let fixedNavHeight = $alphaNav.outerHeight();
        const headingHeight = $('.az-alphabetical-listing-group-title:first').outerHeight();
        const offsetHeight = fixedNavHeight + headingHeight;
        if ($(window).width() <= breakpoint) {
          fixedNavHeight = 0;
        }
        $root.animate({
          scrollTop: $(href).offset().top - offsetHeight
        }, 500, () => {
          window.location.hash = href;
        });
      });
      if ($('body.toolbar-tray-open').length) {
        $('#az-js-floating-alpha-nav-container').css('top', '79px');
      } else if ($('body.toolbar-horizontal').length) {
        $('#az-js-floating-alpha-nav-container').css('top', '39px');
      }
    }
  };
})(jQuery, Drupal);