/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

var _this = this;

jQuery(document).ready(function ($) {
  $("#az-js-alpha-navigation li").each(function () {
    var groupId = $(_this).children().attr("data-href");

    if ($(groupId).length !== 0) {
      $(_this).removeClass("disabled");
      $(_this).children().attr("tabindex", "0").attr("aria-hidden", "false").attr("href", groupId);
    } else {
      $(_this).addClass("disabled");
      $(_this).children().attr("tabindex", "-1").attr("aria-hidden", "true").removeAttr("href");
    }
  });

  function azAlphabeticalListingCheckNoResults() {
    var _this2 = this;

    var visibleResults = false;
    $(".az-alphabetical-listing-group-title").each(function () {
      if (!$(_this2).hasClass("hide-result")) {
        visibleResults = true;
      }
    });

    if (!visibleResults) {
      $("#az-js-alphabetical-listing-no-results").show();
    } else {
      $("#az-js-alphabetical-listing-no-results").hide();
    }
  }

  function azAlphabeticalListingGroupLoop() {
    var _this3 = this;

    $(".az-alphabetical-listing-group-title").each(function () {
      var thisId = $(_this3).attr("id");
      var thisGroup = thisId.toLowerCase();
      var targetGroup = ".az-alphabetical-letter-group-".concat(thisGroup);
      var visibleChildren = false;
      $(targetGroup).each(function () {
        if (!$(_this3).hasClass("hide-result")) {
          visibleChildren = true;
        }
      });
      var navTarget = $("#az-js-alpha-navigation").find(".page-link[data-href='#".concat(thisId, "']"));

      if (!visibleChildren) {
        $(_this3).hide();
        $(_this3).addClass("hide-result");
        navTarget.parent().addClass("disabled");
        navTarget.attr("tabindex", "-1").attr("aria-hidden", "true").removeAttr("href");
      } else {
        $(_this3).show();
        $(_this3).removeClass("hide-result");
        navTarget.parent().removeClass("disabled");
        navTarget.attr("tabindex", "0").attr("aria-hidden", "false").attr("href", $(_this3).attr("id"));
      }
    });
  }

  $("#az-js-alphabetical-listing-search").keyup(function () {
    var filter = $(_this).val();
    $(".az-js-alphabetical-listing-search-result").each(function () {
      var searchResultText = $(_this).find(".az-alphabetical-listing-item").text();

      if (searchResultText.search(new RegExp(filter, "i")) < 0) {
        $(_this).find("az-alphabetical-listing-item").attr("tabindex", "0");
        $(_this).addClass("hide-result");
        $(_this).hide();
      } else {
        $(_this).find(".az-alphabetical-listing-item").attr("tabindex", "0");
        $(_this).removeClass("hide-result");
        $(_this).show();
      }
    });
    azAlphabeticalListingGroupLoop();
    azAlphabeticalListingCheckNoResults();
  });
  var $root = $("html, body");
  var breakpoint = 600;
  $("#az-js-alpha-navigation a").on("click", function (event) {
    event.preventDefault();
    var $alphaNav = $("#az-js-floating-alpha-nav-container");
    var href = $.attr(_this, "data-href");
    var fixedNavHeight = $alphaNav.outerHeight();
    var headingHeight = $(".az-alphabetical-listing-group-title:first").outerHeight();
    var offsetHeight = fixedNavHeight + headingHeight;

    if ($(window).width() <= breakpoint) {
      fixedNavHeight = 0;
    }

    $root.animate({
      scrollTop: $(href).offset().top - offsetHeight
    }, 500, function () {
      window.location.hash = href;
    });
  });

  if ($("body.toolbar-tray-open").length) {
    $("#az-js-floating-alpha-nav-container").css("top", "79px");
  } else if ($("body.toolbar-horizontal").length) {
    $("#az-js-floating-alpha-nav-container").css("top", "39px");
  }
});