# The 'type' should be "label" for short meta tags and "text" for ones which
# could get longer, especially ones which use a textarea field instead of a
# textfield.

metatag.metatag_tag.pinterest_description:
  type: text
  label: 'Pinterest: Description'
metatag.metatag_tag.pinterest_id:
  type: text
  label: 'Pinterest: ID'
metatag.metatag_tag.pinterest_media:
  type: text
  label: 'Pinterest: Media'
metatag.metatag_tag.pinterest_nohover:
  type: text
  label: 'Pinterest: No hover'
metatag.metatag_tag.pinterest_nopin:
  type: text
  label: 'Pinterest: No pin'
metatag.metatag_tag.pinterest_nosearch:
  type: text
  label: 'Pinterest: No search'
metatag.metatag_tag.pinterest_url:
  type: text
  label: 'Pinterest: URL'
