<?php

/**
 * @file
 * Install, update and uninstall functions for az_person module.
 */

/**
 * Delete legacy view reorder people block in favor of contextual links.
 */
function az_person_update_920501() {
  \Drupal::service('config.factory')->getEditable('block.block.az_person_reorder_notification')->delete();
  return t('Deleted legacy view reorder people block in favor of contextual links.');
}
