# Schema for the configuration files of the Quickstart Person Profile Import module.
az_person_profile_import.settings:
  type: config_object
  label: 'Quickstart Person Profile Import settings'
  mapping:
    endpoint:
      type: string
      label: 'Profiles Endpoint'
    apikey:
      type: string
      label: 'API Key'
