# Default value.
field.value.az_stat:
  type: mapping
  label: Default value
  mapping:
    stat_heading:
      type: string
      label: Stat Title
    stat_description:
      type: text
      label: Stat Body
    media:
      type: integer
      label: Stat Media
    stat_source:
      type: string
      label: Stat Link Title
    link_uri:
      type: string
      label: Stat Link URI
    options:
      type: mapping
      label: Stat Options
      mapping:
        stat_type:
          type: string
          label: Stat Type
        column_span:
          type: string
          label: Column Span
        class:
          type: string
          label: CSS Class
        link_style:
          type: string
          label: Link Style
# Field formatter.
# TODO: add stat style options
field.formatter.settings.az_stat_default:
  type: mapping
  label: Example formatter settings
  mapping:
    foo:
      type: string
      label: Foo
