<?php

/**
 * @file
 * Contains az_paragraphs_splitscreen.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function az_paragraphs_splitscreen_paragraph_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Check for specific paragraph type.
  if ($entity->bundle() === 'az_splitscreen') {
    $build['#attached']['library'][] = 'az_paragraphs_splitscreen/az_paragraphs_splitscreen';
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function az_paragraphs_splitscreen_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'az_paragraphs_splitscreen');
  // Find all .html.twig files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.html.twig', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Copy default paragraph registry entry for paragraph entries.
      if (strpos($key, 'paragraph__') === 0) {
        $theme_registry[$key] = $theme_registry['paragraph'];
      }
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
