/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, drupalSettings, window, document, undefined) {
  Drupal.azSelectMenu = Drupal.azSelectMenu || {};
  Drupal.behaviors.azSelectMenu = {
    attach: function attach() {
      var _loop = function _loop(i) {
        var selectFormId = drupalSettings.azSelectMenu.ids[i];
        $("#".concat(selectFormId)).once('az-select-menu', function () {
          console.log(drupalSettings.azSelectMenu.ids[i]);
          $("#".concat(selectFormId, " .js_select_menu_button")).on('touchstart click mouseenter mouseleave focus blur', Drupal.azSelectMenu.handleEvents);
          $("#".concat(selectFormId, "-menu")).on('focus mouseenter', Drupal.azSelectMenu.handleEvents);
          $("#".concat(selectFormId, "-menu")).change(Drupal.azSelectMenu.handleEvents);
          $(document).on('touchstart', Drupal.azSelectMenu.handleEvents);
        });
      };

      for (var i = 0; i < drupalSettings.azSelectMenu.ids.length; i++) {
        _loop(i);
      }

      ;
    }
  };

  Drupal.azSelectMenu.handleEvents = function (e) {
    console.log(e);
    var $this = $(this);

    if (e.type === 'touchstart') {
      if ($this.hasClass('btn')) {
        e.stopPropagation();
      } else {
        console.log($this);
        $('.az-select-menu').popover('hide');
        return;
      }
    }

    var $selectForm = $this.closest('form');
    var $selectElement = $selectForm.find('select');
    var $selectBtn = $selectForm.find('.btn');
    var selectElementHref = $selectElement.find('option:selected').data('href');

    if (selectElementHref.indexOf('%3Cnolink%3E') <= 0) {
      $selectForm.popover('hide');
      $selectElement.attr('aria-invalid', 'false');
      $selectBtn.removeClass('disabled');
      $selectBtn.attr('aria-disabled', 'false');
      $selectBtn.removeAttr('disabled');

      switch (e.type) {
        case 'click':
          e.stopImmediatePropagation();
          window.location = selectElementHref;
          break;
      }
    } else {
      $selectBtn.addClass('disabled');
      $selectBtn.attr('aria-disabled', 'true');
      $selectBtn.attr('disabled', true);
      $selectElement.attr('aria-invalid', 'true');

      switch (e.type) {
        case 'click':
          if ($this.hasClass('btn')) {
            $selectForm.popover('show');
            $selectElement.focus();
          }

          break;

        case 'focus':
        case 'mouseenter':
          if ($this.hasClass('btn')) {
            $selectForm.popover('show');
          } else {
            $selectForm.popover('hide');
          }

          break;

        case 'mouseleave':
          $selectForm.popover('hide');
          break;
      }
    }
  };
})(jQuery, Drupal, drupalSettings, this, this.document);