/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, window, document, once) {
  Drupal.azSelectMenu = Drupal.azSelectMenu || {};
  Drupal.behaviors.azSelectMenu = {
    attach: function attach(context, settings) {
      for (var i = 0; i < settings.azSelectMenu.ids.length; i++) {
        var selectFormId = settings.azSelectMenu.ids[i];
        var selectForm = document.querySelector("#".concat(selectFormId));
        once('azSelectMenu', selectForm, context).forEach(function (element) {
          $(element).popover();
          element.addEventListener('focus', function (event) {
            Drupal.azSelectMenu.handleEvents(event);
          }), element.addEventListener('change', function (event) {
            Drupal.azSelectMenu.handleEvents(event);
          }), element.addEventListener('mouseenter', function (event) {
            Drupal.azSelectMenu.handleEvents(event);
          }), button = element.querySelector('button');
          button.addEventListener('click', function (event) {
            Drupal.azSelectMenu.handleEvents(event);
          }), button.addEventListener('touchstart', function (event) {
            Drupal.azSelectMenu.handleEvents(event);
          }), button.addEventListener('mouseenter', function (event) {
            Drupal.azSelectMenu.handleEvents(event);
          }), button.addEventListener('mouseleave', function (event) {
            Drupal.azSelectMenu.handleEvents(event);
          }), button.addEventListener('focus', function (event) {
            Drupal.azSelectMenu.handleEvents(event);
          }), button.addEventListener('blur', function (event) {
            Drupal.azSelectMenu.handleEvents(event);
          }), document.addEventListener('touchstart', function (event) {
            Drupal.azSelectMenu.handleEvents(event);
          }), element.classList.add('processed');
        });
      }

      ;
    }
  };

  Drupal.azSelectMenu.handleEvents = function (event) {
    var $this = $(this);

    if (event.type === 'touchstart') {
      if ($this.hasClass('js_select_menu_button')) {
        event.stopPropagation();
      } else {
        $('.az-select-menu').popover('hide');
        return;
      }
    }

    var $selectForm = $this.closest('form');
    var $selectElement = $selectForm.find('select');
    var $selectBtn = $selectForm.find('button');
    var selectElementHref = $selectElement.children('option:selected').data('href');
    $selectForm.popover('show');
    console.log(selectElementHref);
    console.log($selectElement.children("option:selected").attr('data-href'));
    console.log($selectElement.find('option:selected').attr('data-href'));

    if (selectElementHref !== undefined) {
      $selectForm.popover('hide');
      $selectElement.attr('aria-invalid', 'false');
      $selectBtn.removeClass('disabled');
      $selectBtn.attr('aria-disabled', 'false');
      $selectBtn.removeAttr('disabled');
      console.log($selectBtn);

      switch (event.type) {
        case 'click':
          event.stopImmediatePropagation();
          window.location = selectElementHref;
          break;
      }
    } else {
      $selectBtn.addClass('disabled');
      $selectBtn.attr('aria-disabled', 'true');
      $selectBtn.attr('disabled', true);
      $selectElement.attr('aria-invalid', 'true');

      switch (event.type) {
        case 'click':
          if ($this.hasClass('btn')) {
            $selectForm.popover('show');
            $selectElement.focus();
          }

          break;

        case 'focus':
        case 'mouseenter':
          if ($this.hasClass('btn')) {
            $selectForm.popover('show');
          } else {
            $selectForm.popover('hide');
          }

          break;

        case 'mouseleave':
          $selectForm.popover('hide');
          break;
      }
    }
  };
})(jQuery, Drupal, this, this.document, once);