webform_scheduled_email.settings:
  type: config_object
  label: 'Webform scheduled email settings'
  mapping:
    schedule_type:
      type: string
      label: 'Scheduled email type (date or date/time)'
