<?php

/**
 * @file
 * Contains az_gutenberg_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function az_gutenberg_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the az_gutenberg_page module.
    case 'help.page.az_gutenberg_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a content type using the Gutenberg page editor.') . '</p>';
      return $output;

    default:
  }
}
