name: az_quickstart
recipe: drupal8
config:
  php: '7.3'
  via: apache:2.4
  webroot: web
  database: mysql:5.7
  xdebug: false
  env_file:
  - env/lando.env
services:
  appserver:
    composer:
      hirak/prestissimo: ^0.3.9
    overrides:
      volumes:
        # Don't share our host working directory as /app. We want /app empty for composer.
        - /app
        # Instead share our host working directory as a standalone package.
        - .:/usr/local/quickstart-install-profile
    build:
      # Create a new quickstart project and use the installation profile as a non-packagist repository.
      # Use the matching scaffolding branch if available.
      - BRANCH_NAME=$(git -C /usr/local/quickstart-install-profile rev-parse --abbrev-ref HEAD); if [ $(git ls-remote --heads https://github.com/az-digital/az-quickstart-scaffolding.git $BRANCH_NAME | wc -l) = 1 ]; then SCAFFOLD_BRANCH="$BRANCH_NAME"; else SCAFFOLD_BRANCH="master"; fi; git clone --branch $SCAFFOLD_BRANCH https://github.com/az-digital/az-quickstart-scaffolding.git /app
      - composer config repositories.localdev path /usr/local/quickstart-install-profile && composer require --no-update drupal/core-recommended:\>\=8.5.0 zaporylie/composer-drupal-optimizations:1.1.1 az-digital/az_quickstart:\*@dev
      - composer install
tooling:
  # Provide a command to install Drupal.
  # Current versions of the Bitnami MySQL container sometimes signal
  # healthy before MySQL is fully started. This can result in MySQL errors
  # in a race condition if Drupal is installed during the run phase.
  install:
    service: appserver
    cmd: /app/vendor/bin/drush --root=/app/web site:install --account-mail=noreply@email.arizona.edu --account-name=azadmin --account-pass=lando --db-url=mysql://drupal8:drupal8@database:3306/drupal8 -y --verbose
  # Provide Drush tooling to automatically know the Drupal root.
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush --root=/app/web
  # Provide Drupal console tooling to automatically know the Drupal root.
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal --root=/app/web
  # Provide phpcs tooling to check coding standards.
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs --colors web/profiles/custom/az_quickstart
  # Provide drupal-check tooling to check for deprecated code.
  drupal-check:
    service: appserver
    cmd: /app/vendor/bin/drupal-check web/profiles web/modules web/themes
  # Provide a composer tooling that executes commands in the profile and then updates the attached scaffolding.
  composer:
    service: appserver
    cmd:
      # Run command against the install profile's composer.json - eg. profile dependencies.
      - composer --working-dir=/usr/local/quickstart-install-profile --no-scripts --no-update
      # Now issue a composer update/install for the scaffolding folder to pull in new dependencies.
      # "true" command consumes passed Lando arguments that were only intended to be passed to the previous call.
      - composer --working-dir=/app --no-scripts update && composer --working-dir=/app install && true
