image: proboci/ubuntu:18.04-php7.4
assets:
  - test-credentials.sh
  - migration.settings.php
  - migration.sh
  - terminus.sh
steps:
  - name: Build Arizona Quickstart
    plugin: Script
    script:
      - composer self-update
      - if [ $(git ls-remote --heads https://github.com/az-digital/az-quickstart-scaffolding.git $BRANCH_NAME | wc -l) = 1 ]; then SCAFFOLD_BRANCH="$BRANCH_NAME"; else SCAFFOLD_BRANCH=main; fi
      - if [ $(git ls-remote --heads https://github.com/az-digital/az-quickstart-dev.git $BRANCH_NAME | wc -l) = 1 ]; then DEV_PACKAGE_BRANCH="$BRANCH_NAME"; else DEV_PACKAGE_BRANCH=main; fi
      - git clone --branch $SCAFFOLD_BRANCH https://github.com/az-digital/az-quickstart-scaffolding.git
      - cd az-quickstart-scaffolding
      - composer config repositories.az_quickstart vcs https://github.com/az-digital/az_quickstart.git
      - composer config use-github-api false
      - composer require --no-update drupal/core-recommended:* zaporylie/composer-drupal-optimizations:* az-digital/az_quickstart:dev-${BRANCH_NAME}
      - composer require --no-update --dev az-digital/az-quickstart-dev:dev-${DEV_PACKAGE_BRANCH}
      - composer install -o
  - name: Run PHP_CodeSniffer coding standards checks
    plugin: Shell
    command: 'cd $SRC_DIR/az-quickstart-scaffolding ; ./vendor/bin/phpcs -p --colors web/profiles/custom/az_quickstart'
  - name: Run PHPStan code quality checks
    plugin: Script
    script:
      - cd $SRC_DIR/az-quickstart-scaffolding
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/phpstan analyse --configuration web/profiles/custom/az_quickstart/phpstan.neon web/profiles/custom/az_quickstart
  - name: Run ESLint
    plugin: Script
    script:
      - sudo npm cache clean -f --silent --no-progress
      - sudo npm install -g --no-progress n
      - sudo n 12.18.1
      - npm install --no-progress --global eslint-config-drupal-bundle
      - cd $SRC_DIR/az-quickstart-scaffolding/web/profiles/custom/az_quickstart && eslint --color .
  - name: Install Arizona Quickstart
    plugin: Drupal
    drupalVersion: 8
    subDirectory: az-quickstart-scaffolding/web
    runInstall: true
    profileName: az_quickstart
    installArgs: "--site-name='Quickstart Review' --account-name=azadmin --account-pass=azadmin --verbose --yes -n"
  - name: Post-Installation Steps
    plugin: Script
    script:
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:create azcontenteditor --password="azcontenteditor"
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_content_editor azcontenteditor
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:create azcontentadmin --password="azcontentadmin"
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_content_editor azcontentadmin
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_content_admin azcontentadmin
      - chown www-data:www-data -R /var/www/html/sites/default/files
  - name: Run PHPUnit Tests
    plugin: Script
    script:
      - mkdir -p /var/www/html/sites/simpletest
      - chown www-data:www-data -R /var/www/html/sites/simpletest
      - mkdir -p /var/www/html/sites/default/files/simpletest
      - chown www-data:www-data -R /var/www/html/sites/default/files/simpletest
      - sudo CHROMEDRIVER_VERSION=LATEST_$(/usr/bin/google-chrome --product-version | cut -d . -f 1-3) npm install --no-progress --unsafe-perm --global chromedriver
      - sudo apt-get install daemonize
      - source $ASSET_DIR/test-credentials.sh
      - export SIMPLETEST_BASE_URL="http://localhost"
      - export SIMPLETEST_DB="mysql://${TEST_DATABASE_USER}:${TEST_DATABASE_PASS}@localhost/${TEST_DATABASE_NAME}"
      - export MINK_DRIVER_ARGS_WEBDRIVER='["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless","--no-sandbox"]}}, "http://localhost:9515"]'
      - daemonize /usr/local/bin/chromedriver --log-path=/tmp/chromedriver.log --verbose --whitelisted-ips="127.0.0.1"
      - cd /var/www/html/profiles/custom/az_quickstart
      - sudo -u www-data -E find $SRC_DIR/az-quickstart-scaffolding/web/profiles/custom/az_quickstart/ -name "*Test.php" | sudo -u www-data -E $SRC_DIR/az-quickstart-scaffolding/vendor/bin/fastest -p 10 -vvv "$SRC_DIR/az-quickstart-scaffolding/vendor/bin/phpunit {} --colors="always" --verbose --do-not-cache-result;"
  - name: Log in to terminus
    command: 'source ${ASSET_DIR}/terminus.sh; terminus auth:login --machine-token=${TERMINUS_TOKEN}'
  - name: Migration Tests
    plugin: Script
    script:
      - source ${ASSET_DIR}/migration.sh
      - terminus connection:info ${MIGRATION_SOURCE_SITE_NAME}.dev --fields 'mysql_host,mysql_password,mysql_port,mysql_database,mysql_username' --format=json > /tmp/migration_config.json
      - mkdir -p /var/www/html/sites/migration && cd /var/www/html/sites
      - cp example.sites.php sites.php
      - echo "\$sites['$BUILD_ID--site-migration.probo.build'] = 'migration';" >> sites.php
      - cp ${ASSET_DIR}/migration.settings.php migration/settings.php
      - cd migration
      - drush site:install az_quickstart --site-name='Quickstart Migration' --account-name=azadmin --account-pass=azadmin --verbose --yes -n
      - chown www-data:www-data -R /var/www/html/sites/migration/files
      - terminus env:wake ${MIGRATION_SOURCE_SITE_NAME}.dev
      - drush -y en az_migration
      - drush -y cset az_migration.settings migrate_d7_protocol "https"
      - drush -y cset az_migration.settings migrate_d7_filebasepath "dev-${MIGRATION_SOURCE_SITE_NAME}.pantheonsite.io/"
      - drush -y cset az_migration.settings migrate_d7_public_path "sites/default/files"
      - drush mim --group=az_migration
      - echo "https://${BUILD_ID}--site-migration.probo.build/"
