image: proboci/ubuntu:18.04-php7.3
assets:
  - credentials.sh
steps:
  - name: Build Arizona Quickstart
    plugin: Script
    script:
      - composer self-update
      - composer global require hirak/prestissimo
      - if [ $(git ls-remote --heads https://github.com/az-digital/az-quickstart-scaffolding.git $BRANCH_NAME | wc -l) = 1 ]; then SCAFFOLD_BRANCH="$BRANCH_NAME"; else SCAFFOLD_BRANCH=main; fi
      - git clone --branch $SCAFFOLD_BRANCH https://github.com/az-digital/az-quickstart-scaffolding.git
      - cd az-quickstart-scaffolding
      - composer config repositories.az_quickstart vcs https://github.com/az-digital/az_quickstart.git
      - composer config use-github-api false
      - composer require --no-update drupal/core-recommended:* zaporylie/composer-drupal-optimizations:* az-digital/az_quickstart:dev-${BRANCH_NAME}
      - composer install -o
  - name: Drupal Coding Standards
    plugin: Shell
    command: 'cd $SRC_DIR/az-quickstart-scaffolding ; ./vendor/bin/phpcs -p --colors web/profiles/custom/az_quickstart'
  - name: Run ESLint
    plugin: Script
    script:
      - sudo npm cache clean -f --silent --no-progress
      - sudo npm install -g --no-progress n
      - sudo n 12.18.1
      - npm install --no-progress --global eslint-config-drupal-bundle
      - cd $SRC_DIR/az-quickstart-scaffolding/web/profiles/custom/az_quickstart && eslint --color .
  - name: Check For Deprecated Code
    plugin: Script
    script:
      - cd $SRC_DIR/az-quickstart-scaffolding
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drupal-check web/profiles
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/phpstan analyse --configuration web/profiles/custom/az_quickstart/phpstan.neon web/modules web/themes
  - name: Install Arizona Quickstart
    plugin: Drupal
    drupalVersion: 8
    subDirectory: az-quickstart-scaffolding/web
    runInstall: true
    profileName: az_quickstart
    installArgs: "--site-name='Quickstart Review' --account-name=azadmin --account-pass=azadmin --verbose --yes -n"
  - name: Post-Installation Steps
    plugin: Script
    script:
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:create azcontenteditor --password="azcontenteditor"
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_content_editor azcontenteditor
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:create azcontentadmin --password="azcontentadmin"
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_content_editor azcontentadmin
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_content_admin azcontentadmin
      - chown www-data:www-data -R /var/www/html/sites/default/files
  - name: Run PHPUnit Tests
    plugin: Script
    script:
      - mkdir -p /var/www/html/sites/simpletest
      - chown www-data:www-data -R /var/www/html/sites/simpletest
      - source $ASSET_DIR/credentials.sh
      - export SIMPLETEST_BASE_URL="http://localhost"
      - export SIMPLETEST_DB="mysql://${DATABASE_USER}:${DATABASE_PASS}@localhost/${DATABASE_NAME}"
      - cd /var/www/html/profiles/custom/az_quickstart
      - sudo -u www-data -E $SRC_DIR/az-quickstart-scaffolding/vendor/bin/phpunit --colors="always" --verbose
