image: proboci/ubuntu:18.04-php7.4
assets:
  - test-credentials.sh
  - migration.settings.php
  - migration.sh
  - terminus.sh
steps:
  - name: Build Arizona Quickstart
    plugin: Script
    script:
      - composer self-update
      - if [ $(git ls-remote --heads https://github.com/az-digital/az-quickstart-scaffolding.git $BRANCH_NAME | wc -l) = 1 ]; then SCAFFOLD_BRANCH="$BRANCH_NAME"; else SCAFFOLD_BRANCH=main; fi
      - git clone --branch $SCAFFOLD_BRANCH https://github.com/az-digital/az-quickstart-scaffolding.git
      - cd az-quickstart-scaffolding
      - composer config repositories.az_quickstart vcs https://github.com/az-digital/az_quickstart.git
      - composer config use-github-api false
      - composer require --no-update drupal/core-recommended:* zaporylie/composer-drupal-optimizations:* az-digital/az_quickstart:dev-${BRANCH_NAME}
      - composer install -o
  - name: Run PHP_CodeSniffer coding standards checks
    plugin: Shell
    command: 'cd $SRC_DIR/az-quickstart-scaffolding ; ./vendor/bin/phpcs -p --colors web/profiles/custom/az_quickstart'
  - name: Run PHPStan code quality checks
    plugin: Script
    script:
      - cd $SRC_DIR/az-quickstart-scaffolding
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/phpstan analyse --configuration web/profiles/custom/az_quickstart/phpstan.neon web/profiles/custom/az_quickstart
  - name: Run ESLint
    plugin: Script
    script:
      - sudo npm cache clean -f --silent --no-progress
      - sudo npm install -g --no-progress n
      - sudo n 12.22.6
      - cd $SRC_DIR/az-quickstart-scaffolding/web/profiles/custom/az_quickstart
      - yarn install
      - yarn run eslint --color .
  - name: Install Arizona Quickstart
    plugin: Drupal
    drupalVersion: 8
    subDirectory: az-quickstart-scaffolding/web
    runInstall: true
    profileName: az_quickstart
    installArgs: "--site-name='Quickstart Review' --account-name=azadmin --account-pass=azadmin --verbose --yes -n"
  - name: Post-Installation Steps
    plugin: Script
    script:
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush -y -n pm:enable az_demo
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:create azcontenteditor --password="azcontenteditor"
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_content_editor azcontenteditor
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:create azcontentadmin --password="azcontentadmin"
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_content_editor azcontentadmin
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_content_admin azcontentadmin
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:create azuseradmin --password="azuseradmin"
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_content_editor azuseradmin
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_content_admin azuseradmin
      - $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush user:role:add az_user_admin azuseradmin
      - chown www-data:www-data -R /var/www/html/sites/default/files
  - name: Check for PHP errors and notices
    plugin: Script
    script:
      # Load some known demo URL paths
      - curl -I http://localhost
      - curl -I http://localhost/user
      - curl -I http://localhost/people
      - curl -I http://localhost/people-list
      - curl -I http://localhost/pages/text
      - curl -I http://localhost/pages/text-background
      - curl -I http://localhost/pages/text-media
      - curl -I http://localhost/pages/card-decks
      - curl -I http://localhost/pages/accordions
      - curl -I http://localhost/pages/photo-galleries
      - curl -I http://localhost/page-grid
      - curl -I http://localhost/page-list
      - curl -I http://localhost/news
      - curl -I http://localhost/calendar
      - curl -I http://localhost/pages/annual-events
      # Check for PHP watchdog entries
      - if [ -z "$($SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush -n watchdog:list --type=php)" ]; then echo "No PHP notices/errors logged."; else $SRC_DIR/az-quickstart-scaffolding/vendor/bin/drush -n watchdog:list --type=php && echo "PHP notices/errors found in log." >&2 && exit 1; fi
  - name: Run PHPUnit Tests
    plugin: Script
    script:
      - mkdir -p /var/www/html/sites/simpletest
      - chown www-data:www-data -R /var/www/html/sites/simpletest
      - mkdir -p /var/www/html/sites/default/files/simpletest
      - chown www-data:www-data -R /var/www/html/sites/default/files/simpletest
      - sudo CHROMEDRIVER_VERSION=LATEST_$(/usr/bin/google-chrome --product-version | cut -d . -f 1-3) npm install --no-progress --unsafe-perm --global chromedriver
      - sudo apt-get install daemonize
      - source $ASSET_DIR/test-credentials.sh
      - export SIMPLETEST_BASE_URL="http://localhost"
      - export SIMPLETEST_DB="mysql://${TEST_DATABASE_USER}:${TEST_DATABASE_PASS}@localhost/${TEST_DATABASE_NAME}"
      - export MINK_DRIVER_ARGS_WEBDRIVER='["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--disable-dev-shm-usage","--headless","--no-sandbox"]}}, "http://localhost:9515"]'
      - daemonize /usr/local/bin/chromedriver --log-path=/tmp/chromedriver.log --verbose --whitelisted-ips="127.0.0.1"
      - cd /var/www/html/profiles/custom/az_quickstart
      - export RUN_TESTS_CONCURRENCY=10
      - mysqladmin create ${TEST_DATABASE_NAME}
      - sudo -u www-data -E find $SRC_DIR/az-quickstart-scaffolding/web/profiles/custom/az_quickstart/ -name "*Test.php" | sudo -u www-data -E $SRC_DIR/az-quickstart-scaffolding/vendor/bin/fastest -p 10 -vvv "$SRC_DIR/az-quickstart-scaffolding/vendor/bin/phpunit {} --colors="always" --verbose --do-not-cache-result;"
  - name: Log in to terminus
    command: 'source ${ASSET_DIR}/terminus.sh; terminus auth:login --machine-token=${TERMINUS_TOKEN}'
  - name: Migration Tests
    plugin: Script
    script:
      - source ${ASSET_DIR}/migration.sh
      - terminus connection:info ${MIGRATION_SOURCE_SITE_NAME}.dev --fields 'mysql_host,mysql_password,mysql_port,mysql_database,mysql_username' --format=json > /tmp/migration_config.json
      - mkdir -p /var/www/html/sites/migration && cd /var/www/html/sites
      - cp example.sites.php sites.php
      - echo "\$sites['$BUILD_ID--site-migration.probo.build'] = 'migration';" >> sites.php
      - cp ${ASSET_DIR}/migration.settings.php migration/settings.php
      - cd migration
      - drush site:install az_quickstart --site-name='Quickstart Migration' --account-name=azadmin --account-pass=azadmin --verbose --yes -n
      - chown www-data:www-data -R /var/www/html/sites/migration/files
      - terminus env:wake ${MIGRATION_SOURCE_SITE_NAME}.dev
      - drush -y en az_migration
      - drush -y cset az_migration.settings migrate_d7_protocol "https"
      - drush -y cset az_migration.settings migrate_d7_filebasepath "dev-${MIGRATION_SOURCE_SITE_NAME}.pantheonsite.io/"
      - drush -y cset az_migration.settings migrate_d7_public_path "sites/default/files"
      - drush mim --group=az_migration
      - echo "https://${BUILD_ID}--site-migration.probo.build/"
