field.formatter.settings.az_background_media:
  type: mapping
  label: 'Az Paragraphs Background Media'
  mapping:
    image_style:
      type: string
      label: 'Responsive image style'
    css_settings:
      type: mapping
      label: 'Default CSS Settings'
      mapping:
        bg_image_selector:
          type: string
          label: 'CSS Selector'
        bg_image_color:
          type: string
          label: 'Color'
        bg_image_x:
          type: string
          label: 'Horizontal Alignment'
        bg_image_y:
          type: string
          label: 'Vertical Alignment'
        bg_image_attachment:
          type: string
          label: 'Background Attachment'
        bg_image_repeat:
          type: string
          label: 'Background Repeat'
        bg_image_background_size:
          type: string
          label: 'Background Size'
        bg_image_gradient:
          type: string
          label: 'Gradient'
        bg_image_important:
          type: boolean
          label: 'Add "!important" to the background property.'