<?php

/**
 * @file
 * Upgrades core migrations to migrate as much menu links as possible.
 */

use Drupal\migmag_menu_link_migrate\MigMagMenuLinkMigrate;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_help().
 */
function migmag_menu_link_migrate_help($route_name) {
  switch ($route_name) {
    case 'help.page.migmag_menu_link_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>';
      $output .= t(
        'Modifies Drupal core\'s menu link migrations to migrate as many menu links as possible. See the <a href=":documentation">online documentation for Migrate Magician Menu Link Migrate module</a>.',
        [
          ':documentation' => 'https://drupal.org/docs/contributed-modules/migrate-magician/migrate-magician-menu-link-migrate-130',
        ]
      );
      $output .= '</p>';
      return $output;
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function migmag_menu_link_migrate_migration_plugins_alter(array &$migrations) {
  MigMagMenuLinkMigrate::applyMenuLinkMigrationConfigurationFixes($migrations, TRUE);
}

/**
 * Implements hook_migrate_prepare_row().
 */
function migmag_menu_link_migrate_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  MigMagMenuLinkMigrate::prepareMenuLinkStubMigration($row, $migration);
}
