<?php

/**
 * @file
 * Contains az_accordion.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function az_accordion_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the az_accordion module.
    case 'help.page.az_accordion':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom field plugins and theme template for accordion.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function az_accordion_theme($existing, $type, $theme, $path) {
  return [
    'az_accordion' => [
      'variables' => [
        'attributes' => [],
        'title' => NULL,
        'body' => NULL,
        'accordion_item_id' => NULL,
        'collapsed' => TRUE,
        'aria_expanded' => 'false',
        'aria_controls' => NULL,
      ],
      'deprecations' => [
        'aria_controls' => "'aria_controls' is deprecated in az_quickstart:2.12.0 and is removed from az_quickstart:2.13.0. Use 'accordion_item_id' instead. See https://github.com/az-digital/az_quickstart/issues/3807.",
      ],
      'template' => 'az-accordion',
    ],
  ];
}
