<?php

/**
 * @file
 * Contains az_custom_menu_block.module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function az_custom_menu_block_preprocess_block(&$variables) {
  if($variables['base_plugin_id'] === 'menu_block') {
    if($variables['configuration']['az_custom_menu_block'] === 'az_custom_menu_block'){
      $variables['title_attributes']['class'][] = 'h4';
      $variables['title_attributes']['class'][] = 'mt-0';
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Adds metadata about az_custom_menu_blocks.
 */
function az_custom_menu_block_preprocess_field__block_content__field_az_block__az_custom_menu_block(&$variables) {
  if($variables['element']['#bundle'] && $variables['element']['#bundle'] === 'az_custom_menu_block') {
    foreach ($variables['items'] as $delta => $item) {
      $variables['items'][$delta]['content']['#configuration']['az_custom_menu_block'] = 'az_custom_menu_block';
    }
  }
}
