az_flexible_page.settings:
  type: config_object
  label: 'AZ Page settings'
  mapping:
    marketing_page_styles:
      type: mapping
      label: 'Marketing Campaign Page styles'
      mapping:
        enabled:
          type: boolean
          label: 'Marketing Campaign Page styles enabled'
