data_source: maxmind_geoip2_bin_db
roles_to_geolocate:
  anonymous: anonymous
  authenticated: authenticated
  az_profile_editor: '0'
  az_content_editor: '0'
  az_content_admin: '0'
  az_user_admin: '0'
  az_html_admin: '0'
  administrator: '0'
save_user_location_creation: false
roles_in_debug_mode:
  anonymous: false
  authenticated: false
  az_profile_editor: false
  az_content_editor: false
  az_content_admin: false
  az_user_admin: false
  az_html_admin: false
  administrator: false
roles_in_debug_mode_ip:
  anonymous: ''
  authenticated: ''
  az_profile_editor: ''
  az_content_editor: ''
  az_content_admin: ''
  az_user_admin: ''
  az_html_admin: ''
  administrator: ''
allowed_pages: ''
excluded_ips: ''
eu_visitor_dont_save: true
timezone_format: identifier
