/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.azAccordionBlock = {
    attach: function attach() {
      if ($(".accordion").length) {
        var accordionIdCounter = 1;

        $(".accordion").each(function () {
          var thisAccordionId = "accordion_" + accordionIdCounter;
          $(this).attr("id", thisAccordionId);

          var accordionHeadingIdCounter = 1;
          $(this).find(".card").each(function () {
            var thisAccordionHeadingId = "accordion_" + accordionIdCounter + "_heading_" + accordionHeadingIdCounter;
            $(this).find(".card-header").attr("id", thisAccordionHeadingId);

            var thisAccordionCollapseId = "accordion_" + accordionIdCounter + "_collapse_" + accordionHeadingIdCounter;

            $(this).find("button.btn-link").attr("data-target", "#" + thisAccordionCollapseId);
            $(this).find("button.btn-link").attr("data-toggle", "collapse");
            $(this).find("button.btn-link").attr("type", "button");
            $(this).find("button.btn-link").attr("aria-controls", thisAccordionCollapseId);

            $(this).find(".collapse").attr("id", thisAccordionCollapseId);
            $(this).find(".collapse").attr("aria-labeledby", thisAccordionHeadingId);
            $(this).find(".collapse").attr("data-parent", "#" + thisAccordionId);
            accordionHeadingIdCounter += 1;
          });
          accordionIdCounter += 1;
        });
      }
    }
  };
})(jQuery, Drupal);