id: taxonomy_settings
label: Taxonomy configuration
migration_tags:
  - Drupal 6
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - taxonomy_override_selector
    - taxonomy_terms_per_page_admin
    - taxonomy_maintain_index_table
  source_module: taxonomy
process:
  override_selector: taxonomy_override_selector
  terms_per_page_admin: taxonomy_terms_per_page_admin
  maintain_index_table:
    plugin: default_value
    default_value: true
    source: taxonomy_maintain_index_table
destination:
  plugin: config
  config_name: taxonomy.settings
