<?php

/**
 * @file
 * Contains az_google_tag.module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_toolbar_alter().
 */
function az_google_tag_toolbar_alter(&$items) {
  if (\Drupal::service('module_handler')->moduleExists('az_core')) {
    $site_url = \Drupal::request()->getHost();
    $items['az_quickstart']['tray']['az_links']['#links']['analytics'] = [
      'title' => t('Analytics Dashboard'),
      'url' => Url::fromUri('https://lookerstudio.google.com/reporting/ef02c272-afe4-4862-b4bd-8706e3436b2f/page/nbaTD', [
        'query' => [
          'params' => '{"df21":"include%EE%80%800%EE%80%80IN%EE%80%80' . $site_url . '"}',
        ],
        'absolute' => TRUE,
      ]),
      'attributes' => [
        'title' => t('Site Analytics Dashboard'),
        'target' => t('_blank'),
      ],
    ];
  }
}

/**
 * Checks if the consent mode config setting is enabled for any Google Tags.
 *
 * @return bool
 *   TRUE if consent mode is enabled for any Google Tags, FALSE otherwise.
 */
function az_google_tag_consent_mode_enabled() {
  $google_tag_storage = \Drupal::entityTypeManager()->getStorage('google_tag_container');
  $consent_enabled_count = count(
  // Find enabled Google tags with a consent mode value of 1 or TRUE.
    $google_tag_storage->loadByProperties([
      'advanced_settings.consent_mode' => [1, TRUE],
      'status' => [1, TRUE],
    ])
  );
  return $consent_enabled_count > 0;
}
