#
# Schema for the AZ Filters filter widgets.
#
better_exposed_filters.filter.az_finder_tid_widget:
  label: 'Quickstart Finder Term ID Widget'
  type: better_exposed_filters_filter_widget
  mapping:
    select_all_none:
      type: boolean
      label: 'Add select all/none links'
    select_all_none_nested:
      type: boolean
      label: 'Add select all/none links to hierarchical lists'
    display_inline:
      type: boolean
      label: 'Display checkbox/radio options inline'

