views.exposed_form.az_better_exposed_filters:
  type: views.exposed_form.bef
  label: 'Quickstart Exposed Filters'
  mapping:
    reset_button_position:
      type: string
      label: 'Reset Button Position'
    min_text_length:
      type: integer
      label: 'Minimum Text Length for Active Filter Counter'
    reset_button_counter:
      type: boolean
      label: 'Show Active Filter Counter'
    orientation:
      type: string
      label: 'Orientation'
    skip_link:
      type: boolean
      label: 'Add Skip Link'
    skip_link_text:
      type: string
      label: 'Skip Link Text'
    skip_link_id:
      type: string
      label: 'Skip Link ID'
