<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'field_config.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'field_config_instance.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'menu_custom.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'menu_links.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'node.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'node_revision.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'node_type.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'role.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'role_permission.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'system.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'users.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'users_roles.php';
include 'd7-menu-link-db' . DIRECTORY_SEPARATOR . 'variable.php';
