name: 'Configuration Synchronizer'
type: module
description: 'Synchronize your site with updated configuration provided by modules and themes.'
core_version_requirement: ^9 || ^10 || ^11
package: Configuration
configure: config_distro.import
dependencies:
  - config_distro:config_distro_filter
  - config_merge:config_merge
  - config_normalizer:config_normalizer
  - config_provider:config_provider
  - config_snapshot:config_snapshot
  - config_update:config_update

# Information added by Drupal.org packaging script on 2025-03-27
version: '3.0.0-alpha4'
project: 'config_sync'
datestamp: 1743110768
