/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function ($, Drupal, drupalSettings, once) {
  Drupal.behaviors.trellisDatePicker = {
    attach: function attach(context) {
      $(once('aztrellisdate', '.az-trellis-daterange', context)).each(function () {
        var begin = this;
        var id = $(this).data('az-trellis-daterange-end');
        var end = $("#".concat(id)).get(0);
        var picker = new easepick.create({
          element: begin,
          css: drupalSettings.trellisDatePicker.css,
          zIndex: 10,
          RangePlugin: {
            elementEnd: end
          },
          plugins: ['RangePlugin']
        });
      });
    }
  };
})(jQuery, Drupal, drupalSettings, once);