/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
((Drupal, drupalSettings, once) => {
  Drupal.behaviors.trellisDatePicker = {
    attach(context) {
      const elements = once('aztrellisdate', '.az-trellis-daterange', context);
      elements.forEach(element => {
        const begin = element;
        const id = element.dataset.azTrellisDaterangeEnd;
        const end = document.getElementById(id);
        const picker = new easepick.create({
          element: begin,
          css: drupalSettings.trellisDatePicker.css,
          zIndex: 10,
          RangePlugin: {
            elementEnd: end
          },
          plugins: ['RangePlugin']
        });
      });
    }
  };
})(Drupal, drupalSettings, once);