/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(Drupal => {
  const Z_INDEX = 1261;
  const TOP_POSITION = '48.5%';
  const LEFT_POSITION = '49%';
  const SPINNER_SIZE = '3rem';
  const spinnerPositionClass = 'js-az-spinner-position';
  const style = document.createElement('style');
  style.textContent = `
    .${spinnerPositionClass} {
      position: fixed;
      z-index: ${Z_INDEX};
      top: ${TOP_POSITION};
      left: ${LEFT_POSITION};
    }
  `;
  document.head.appendChild(style);
  Drupal.theme.ajaxProgressIndicatorFullscreen = () => `
    <div class="${spinnerPositionClass}">
      <div class="spinner-border text-info" style="width: ${SPINNER_SIZE}; height: ${SPINNER_SIZE};" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>`;
})(Drupal);