/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function (Drupal) {
  var Z_INDEX = 1261;
  var TOP_POSITION = '48.5%';
  var LEFT_POSITION = '49%';
  var SPINNER_SIZE = '3rem';
  var spinnerPositionClass = 'js-az-spinner-position';
  var style = document.createElement('style');
  style.textContent = "\n    .".concat(spinnerPositionClass, " {\n      position: fixed;\n      z-index: ").concat(Z_INDEX, ";\n      top: ").concat(TOP_POSITION, ";\n      left: ").concat(LEFT_POSITION, ";\n    }\n  ");
  document.head.appendChild(style);
  Drupal.theme.ajaxProgressIndicatorFullscreen = function () {
    return "\n    <div class=\"".concat(spinnerPositionClass, "\">\n      <div class=\"spinner-border text-info\" style=\"width: ").concat(SPINNER_SIZE, "; height: ").concat(SPINNER_SIZE, ";\" role=\"status\">\n        <span class=\"visually-hidden\">Loading...</span>\n      </div>\n    </div>");
  };
})(Drupal);