# Schema for the configuration files of the dblog module.

dblog.settings:
  type: config_object
  label: 'Database logging settings'
  mapping:
    row_limit:
      type: integer
      label: 'Database log messages to keep'
      constraints:
        Range:
          min: 0
  constraints:
    FullyValidatable: ~
