<?php

/**
 * @file
 * Contains az_opportunity.module.
 */

/**
 * Implements hook_preprocess_node() for az_opportunity nodes.
 */
function az_opportunity_preprocess_node__az_opportunity(&$variables) {

  // Attach the opportunity CSS library for az_opportunity node renderings.
  $variables['#attached']['library'][] = 'az_opportunity/az_opportunity';
  //dpr($variables);
  //if(isEmpty($variables['elements']['field_az_application_date'][0])) {
    
  //}
}

/**
 * Implements template_preprocess_views_view() for az_opportunity views.
 */
function az_opportunity_preprocess_views_view(&$variables) {

  $view = $variables['view'];
  $id = $view->storage->id();

  if ($id === 'az_opportunity') {
    $variables['#attached']['library'][] = 'az_opportunity/az_opportunity';
  }
}

/**
 * Implements hook_preprocess_field() for field_az_application_date.
 *
 * Displays "TBD" when the field is empty.
 */
//function az_opportunity_preprocess_field__field_az_application_date(&$variables) {
//  dpr($variables);
//}