<?php

/**
 * @file
 * Contains az_opportunity.module.
 */

/**
 * Implements hook_preprocess_node() for az_opportunity nodes.
 */
function az_opportunity_preprocess_node__az_opportunity(&$variables) {

	// Attach the opportunity CSS library for az_opportunity node renderings.
	$variables['#attached']['library'][] = 'az_opportunity/az_opportunity';
}

/**
 * Implements template_preprocess_views_view().
 *
 * Ensure that views that render az_opportunity also get the CSS library.
 */
function az_opportunity_preprocess_views_view(&$variables) {

	$view = $variables['view'];
	$id = $view->storage->id();

	if ($id === 'az_opportunity') {
		$variables['#attached']['library'][] = 'az_opportunity/az_opportunity';
	}
}