/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function (Drupal, once) {
  Drupal.behaviors.az_vimeo_video_bg = {
    attach: function attach() {
      function initVimeoBackgrounds() {
        var defaultAspectRatio = 16 / 9;
        function vimeoError(error) {
          switch (error.name) {
            case 'PasswordError':
              console.log('The Vimeo video is password-protected.');
              break;
            case 'PrivacyError':
              console.log('The Vimeo video is private.');
              break;
            default:
              console.log("Some errors occurred with the Vimeo video: ".concat(error.name));
              break;
          }
        }
        function setDimensions(container) {
          var parentParagraph = container.parentNode;
          var parentHeight = parentParagraph.offsetHeight;
          parentHeight = "".concat(parentHeight.toString(), "px");
          container.style.height = parentHeight;
          if (container.dataset.style === 'bottom') {
            container.style.top = 0;
          }
          var thisPlayer = container.getElementsByClassName('az-video-player')[0].firstChild;
          if (thisPlayer === null) {
            return;
          }
          thisPlayer.style.zIndex = -100;
          var width = container.offsetWidth;
          var height = container.offsetHeight;
          var pWidth = Math.ceil(height * defaultAspectRatio);
          var pHeight = Math.ceil(width / defaultAspectRatio);
          var widthMinuspWidthDividedByTwo = (width - pWidth) / 2;
          widthMinuspWidthDividedByTwo = "".concat(widthMinuspWidthDividedByTwo.toString(), "px");
          var pHeightRatio = (height - pHeight) / 2;
          pHeightRatio = "".concat(pHeightRatio.toString(), "px");
          if (width / defaultAspectRatio < height) {
            thisPlayer.width = pWidth;
            thisPlayer.height = height;
            thisPlayer.style.left = widthMinuspWidthDividedByTwo;
            thisPlayer.style.top = 0;
          } else {
            thisPlayer.height = pHeight;
            thisPlayer.width = width;
            thisPlayer.style.top = pHeightRatio;
            thisPlayer.style.left = 0;
          }
        }
        if (window.screen && window.screen.width > 768) {
          var defaultOptions = {
            vimeoId: '',
            autopause: false,
            autoplay: true,
            controls: 0,
            loop: true,
            muted: true,
            playButtonClass: 'az-video-play',
            pauseButtonClass: 'az-video-pause'
          };
          var bgVideoParagraphs = document.getElementsByClassName('az-js-vimeo-video-background');
          var tag = document.createElement('script');
          tag.src = 'https://player.vimeo.com/api/player.js';
          document.head.appendChild(tag);
          tag.onload = function () {
            Array.from(bgVideoParagraphs).forEach(function (element) {
              var parentParagraph = element.parentNode;
              var vimeoId = element.dataset.vimeoVideoId;
              var videoPlayer = element.getElementsByClassName('az-video-player')[0];
              var VimeoPlayer = window.Vimeo;
              element.player = new VimeoPlayer.Player(videoPlayer, {
                id: vimeoId,
                autopause: defaultOptions.autopause,
                autoplay: element.dataset.autoplay === 'true',
                controls: 0,
                loop: defaultOptions.loop,
                muted: defaultOptions.muted
              });
              element.player.on('bufferend', function () {
                setDimensions(element);
                parentParagraph.classList.add('az-video-playing');
              });
              var playButtons = element.getElementsByClassName('az-video-play');
              if (playButtons[0]) {
                playButtons[0].addEventListener('click', function (event) {
                  event.preventDefault();
                  element.player.play().catch(function (error) {
                    return vimeoError(error);
                  });
                  parentParagraph.classList.add('az-video-playing');
                  parentParagraph.classList.remove('az-video-paused');
                });
              }
              var pauseButtons = element.getElementsByClassName('az-video-pause');
              if (pauseButtons[0]) {
                pauseButtons[0].addEventListener('click', function (event) {
                  event.preventDefault();
                  element.player.pause().catch(function (error) {
                    return vimeoError(error);
                  });
                  parentParagraph.classList.add('az-video-paused');
                  parentParagraph.classList.remove('az-video-playing');
                });
              }
            });
          };
          var resize = function resize() {
            Array.from(bgVideoParagraphs).forEach(function (element) {
              setDimensions(element);
            });
          };
          window.addEventListener('resize.bgVideo', function () {
            resize();
          });
        }
      }
      once('vimeoTextOnMedia-init', 'body').forEach(initVimeoBackgrounds);
    }
  };
})(Drupal, once);