<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('menu_custom', array(
  'fields' => array(
    'menu_name' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '32',
      'default' => '',
    ),
    'title' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
      'default' => '',
    ),
    'description' => array(
      'type' => 'text',
      'not null' => FALSE,
      'size' => 'normal',
    ),
  ),
  'primary key' => array(
    'menu_name',
  ),
  'mysql_character_set' => 'utf8',
));

$connection->insert('menu_custom')
->fields(array(
  'menu_name',
  'title',
  'description',
))
->values(array(
  'menu_name' => 'features',
  'title' => 'Features',
  'description' => 'Menu items for any enabled features.',
))
->values(array(
  'menu_name' => 'main-menu',
  'title' => 'Main Menu Left',
  'description' => 'The <em>Main</em> menu is used on many sites to show the major sections of the site, often in a top navigation bar.',
))
->values(array(
  'menu_name' => 'management',
  'title' => 'Management',
  'description' => 'The <em>Management</em> menu contains links for administrative tasks.',
))
->values(array(
  'menu_name' => 'menu-academic-programs-menu',
  'title' => 'Academic Programs Menu',
  'description' => '',
))
->values(array(
  'menu_name' => 'menu-admissions-information-menu',
  'title' => 'Admissions Information Menu',
  'description' => '',
))
->values(array(
  'menu_name' => 'menu-business-resources-menu',
  'title' => 'Business Resources Menu',
  'description' => '',
))
->values(array(
  'menu_name' => 'menu-career-training-menu',
  'title' => 'Career Training Menu',
  'description' => '',
))
->values(array(
  'menu_name' => 'menu-community-resources-menu',
  'title' => 'Community Resources Menu',
  'description' => '',
))
->values(array(
  'menu_name' => 'menu-general-information-menu',
  'title' => 'General Information Menu',
  'description' => '',
))
->values(array(
  'menu_name' => 'menu-other-menu',
  'title' => 'Other Menu',
  'description' => 'This menu is used to assign just for Workbench.',
))
->values(array(
  'menu_name' => 'menu-paying-for-college-menu',
  'title' => 'Paying For College Menu',
  'description' => '',
))
->values(array(
  'menu_name' => 'menu-student-life-menu',
  'title' => 'Student Life Menu',
  'description' => '',
))
->values(array(
  'menu_name' => 'menu-super-menu',
  'title' => 'Super Menu',
  'description' => '',
))
->values(array(
  'menu_name' => 'navigation',
  'title' => 'Navigation',
  'description' => 'The <em>Navigation</em> menu contains links intended for site visitors. Links are added to the <em>Navigation</em> menu automatically by some modules.',
))
->values(array(
  'menu_name' => 'user-menu',
  'title' => 'User menu',
  'description' => "The <em>User</em> menu contains links related to the user's account, as well as the 'Log out' link.",
))
->execute();
