<?php

/**
 * @file
 * Az_media.install.
 *
 * Install, update and uninstall functions for
 * az_media module.
 */

/**
 * Implements hook_update_last_removed().
 */
function az_media_update_last_removed() {
  // Remove updates added before 2.6.0.
  return 9201;
}

  /**
 * Enable decorative_image_widget module by default.
 */
function az_media_update_1021301() {
  \Drupal::service('module_installer')->install(['decorative_image_widget']);
}
