<?php

/**
 * @file
 * Contains az_cas_guest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function az_cas_guest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.az_cas_guest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Arizona CAS Guest Authentication module allows site visitors to authenticate via CAS without creating Drupal user accounts.') . '</p>';
      return $output;
  }
}