login_link_enabled: true
login_link_label: 'Log in using University of Arizona WebAuth'
login_success_message: 'Logged in via University of Arizona WebAuth as [cas:username].'
server:
  version: '2.0'
  protocol: https
  hostname: shibboleth.arizona.edu
  port: 443
  path: /webauth
  verify: 0
  cert: ''
gateway:
  enabled: false
  recheck_time: 720
  method: 'client_side'
  paths:
    id: request_path
    pages: '<front>'
    negate: false
forced_login:
  enabled: false
  paths:
    id: request_path
    negate: false
    pages: ''
user_accounts:
  prevent_normal_login: true
  auto_register: false
  email_assignment_strategy: 0
  email_hostname: arizona.edu
  email_attribute: ''
  auto_assigned_roles: {  }
  restrict_password_management: true
  restrict_email_management: true
error_handling:
  login_failure_page: /user/login
  message_validation_failure: 'There was a problem validating your login, please contact a site administrator.'
  message_no_local_account: 'You do not have an account on this website. Please contact a site administrator.'
  message_subscriber_denied_reg: 'You do not have access to log in to this website. Please contact a site administrator if you believe you should have access.'
  message_subscriber_denied_login: 'You do not have access to log in to this website. Please contact a site administrator if you believe you should have access.'
  message_account_blocked: 'Your account is blocked or has not been activated. Please contact a site administrator.'
  message_username_already_exists: 'An account on this website with your username already exists. Please contact a site administrator.'
  message_prevent_normal_login: 'This account must log in using <a href="[cas:login-url]">University of Arizona WebAuth</a>.'
  message_restrict_password_management: 'The requested account is associated with University of Arizona WebAuth and its password cannot be managed from this website.'
logout:
  cas_logout: true
  logout_destination: '<front>'
  enable_single_logout: false
  single_logout_session_lifetime: 25
proxy:
  initialize: false
  can_be_proxied: false
  proxy_chains: ''
advanced:
  debug_log: false
  connection_timeout: 10
