az_publication.az_citation_style.*:
  type: config_entity
  label: 'Quickstart Citation Style config'
  mapping:
    id:
      type: machine_name
      label: 'ID'
    label:
      type: label
      label: 'Label'
    style:
      type: string
      label: 'Style'
    custom:
      type: boolean
      label: 'Custom'
    uuid:
      type: uuid
      label: 'Universally Unique Identifier'
