az_publication.az_citation_style.*:
  type: config_entity
  label: 'Quickstart Citation Style config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    style:
      type: string
      label: 'Style'
    custom:
      type: string
      label: 'Custom Citation Style Language'
    uuid:
      type: string
