<?php

/**
 * @file
 * Contains az_alphabetical_listing.module.
 */

/**
 * Implements template_preprocess_views_view()
 */
function az_alphabetical_listing_preprocess_views_view(&$variables) {
  $view_id = $variables['view']->id();
  if ($view_id === 'az_alphabetical_listing') {
    $variables['#attached']['library'][] = 'az_alphabetical_listing/az_alphabetical_listing';
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function az_alphabetical_listing_theme_registry_alter(&$theme_registry) {
  $module_path = \Drupal::service('extension.list.module')->getPath('az_alphabetical_listing');
  // Find all .html.twig files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.html.twig', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || strpos($theme_registry[$key]['theme path'], 'themes/') === FALSE) {
      // Copy default node registry entry for node entries.
      if (strpos($key, 'node') === 0) {
        $theme_registry[$key] = $theme_registry['node'];
      }
      // Copy default views registry entry for views entries.
      if (strpos($key, 'views') === 0) {
        $theme_registry[$key] = $theme_registry['views_view'];
      }
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
