/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
document.querySelectorAll('.horizontal-tabs-list').forEach(function (tabContainer) {
  tabContainer.setAttribute('aria-label', 'Additional information');
  tabContainer.setAttribute('role', 'tablist');
});
document.querySelectorAll('.horizontal-tab-button').forEach(function (tabSelected, index) {
  tabSelected.setAttribute('role', 'tab');
  tabSelected.setAttribute('aria-selected', index === 0 ? 'true' : 'false');
  tabSelected.setAttribute('aria-controls', "panel".concat(index + 1));
  tabSelected.setAttribute('tabindex', index === 0 ? '0' : '-1');
});