<?php

/**
 * @file
 * Contains az_stat.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function az_stat_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the az_stat module.
    case 'help.page.az_stat':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom field plugins and theme template for stats.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function az_stat_theme($existing, $type, $theme, $path) {
  return [
    'az_stat' => [
      'variables' => [
        'attributes' => [],
        'media' => NULL,
        'column_span' => NULL,
        'stat_hover_style' => NULL,
        'stat_heading' => NULL,
        'stat_alignment' => NULL,
        'stat_title_style' => NULL,
        'stat_description' => NULL,
        'stat_source' => NULL,
        'text_color_override' => NULL,
        'link_url' => NULL,
      ],
      'template' => 'az-stat',
    ],
  ];
}
