<?php

/**
 * @file
 * Install, update, and uninstall functions for az_icons module.
 */

use Drupal\shortcut\Entity\Shortcut;

/**
 * Implements hook_instal().
 *
 * Add shortcut to allow editors to access icon library.
 */
function az_icons_install() {
  $shortcut = Shortcut::create([
    'shortcut_set' => 'default',
    'title' => t('Icon library'),
    'weight' => -18,
    'link' => ['uri' => 'internal:/admin/appearance/ui/icons'],
  ]);
  $shortcut->save();
}
