<?php

/**
 * @file
 * Contains az_news_marketing_cloud.module.
 */

/**
 * Implements hook_theme_registry_alter().
 */
function az_news_marketing_cloud_theme_registry_alter(&$theme_registry) {
  if ($theme_registry['field_multiple_value_form']) {
    if (isset($theme_registry['field_multiple_value_form']['preprocess functions'])) {
      $key = array_search('paragraphs_preprocess_field_multiple_value_form', $theme_registry['field_multiple_value_form']['preprocess functions'], TRUE);
      unset($theme_registry['field_multiple_value_form']['preprocess functions'][$key]);
      $theme_registry['field_multiple_value_form']['preprocess functions'][] = 'paragraphs_preprocess_field_multiple_value_form';
    }
  }

  $module_path = \Drupal::service('extension.list.module')->getPath('az_news_marketing_cloud');
  // Find all .html.twig files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.html.twig', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || strpos($theme_registry[$key]['theme path'], 'themes/') === FALSE) {
      // Copy default paragraph registry entry for paragraph entries.
      if (strpos($key, 'paragraph__') === 0) {
        $theme_registry[$key] = $theme_registry['paragraph'];
      }
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function az_news_marketing_cloud_preprocess_node__view__az_marketing_cloud(&$variables) {
  $node = $variables['node'];
  if ($node->getType() === 'az_news') {
    $token_service = \Drupal::token();
    $variables['az_canonical_url'] = $token_service->replace('[node:az-canonical-url]', ['node' => $node], [], $bubbleable_metadata);
    $variables['az_canonical_summary_link_title'] = $token_service->replace('[node:az-canonical-summary-link-title]', ['node' => $node], [], $bubbleable_metadata);
    $media = $node->field_az_media_image->entity ?? NULL;
    $file = $media->field_media_az_image->entity ?? NULL;
    if (!empty($file)) {
      $uri = $file->getFileUri();
      $variables['file_field_url'] = file_create_url($uri);
    }
  }
}

/**
 * Implements template_preprocess_views_view().
 */
function az_news_marketing_cloud_preprocess_views_view(&$variables) {
  $view = $variables['view'];

  if ($view->id() === 'az_marketing_cloud') {
    $variables['#attached']['library'][] = 'az_news_marketing_cloud/admin';
  }
}
