<?php

/**
 * @file
 * Contains az_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function az_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the az_config module.
    case 'help.page.az_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configuration management customizations for Quickstart components.') . '</p>';
      return $output;

    default:
  }
}
