<?php

/**
 * @file
 * Contains az_multilingual.module.
 */

/**
 * Implements hook_preprocess_HOOK() for links--language-block templates.
 *
 * Override template to include Bootstrap .btn classes on rendered links.
 */
function az_multilingual_preprocess_links__language_block(&$variables) {

  $links = $variables['links'];
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();

  if (!empty($links)) {

    // Include .active class for Bootstrap styling (Drupal uses .is-active)
    if (!empty($lang) && !empty($links[$lang])) {
      $variables['links'][$lang]['link']['#options']['attributes']['class'][] = 'active';
    }
    foreach ($links as $key => $link) {
      $variables['links'][$key]['link']['#options']['attributes']['class'][] = 'btn btn-outline-dark';
    }
  }
}
