<?php

/**
 * @file
 * Contains az_digital_asset_library.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_preprocess_HOOK().
 *
 * Hide default media type provided by IntelligenceBank from media add page.
 *
 * See @link https://github.com/az-digital/az_quickstart/issues/1741
 */
function az_digital_asset_library_preprocess_entity_add_list(&$variables) {
  if (isset($variables['bundles']['ib_dam_embed'])) {
    unset($variables['bundles']['ib_dam_embed']);
  }
}

/**
 * Implements hook_form_alter().
 *
 * Change label text for open browser button.
 * Change dialog title option.
 *
 * See @link drupal.org/project/intelligencebank/issues/3353858
 */
function az_digital_asset_library_form_media_library_add_form_upload_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['ib_dam_container']['asset_browser']['#title'] = t('Add Arizona Digital Asset Library Media');
  $data_dialog_options = Json::decode($form['ib_dam_container']['asset_browser']['#attributes']['data-dialog-options']);
  $data_dialog_options['title'] = 'Arizona Digital Asset Library Browser';
  $form['ib_dam_container']['asset_browser']['#attributes']['data-dialog-options'] = Json::encode($data_dialog_options);
}
