<?php

/**
 * @file
 * Contains az_digital_asset_library.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Custom submit handler to redirect to /admin/content/media.
 */
function az_digital_asset_library_form_submit(array $form, FormStateInterface $form_state) {
  $url = Url::fromRoute('entity.media.collection');
  $form_state->setRedirectUrl($url);
}

/**
 * Implements hook_form_ID_alter().
 *
 * Add custom submit handler to form.
 * Allow using remote media.
 * See
 * @link https://git.drupalcode.org/project/intelligencebank/-/blob/8.x-2.x/modules/ib_dam_media/src/Plugin/EntityBrowser/Widget/IbDamEbWidget.php#L249 @endlink.
 */
function az_digital_asset_library_form_entity_browser_az_digital_asset_library_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'az_digital_asset_library_form_submit';
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Hide default media type provided by IntelligenceBank from media select dialog.
 *
 * See @link https://github.com/az-digital/az_quickstart/issues/1741
 */
function az_digital_asset_library_preprocess_links__media_library_menu(&$variables) {
  if (
    isset($variables['links']) &&
    isset($variables['links']['media-library-menu-ib_dam_embed']) &&
    isset($variables['links']['media-library-menu-ib_dam_embed']['link'])
    ) {
    $variables['links']['media-library-menu-ib_dam_embed']['link']['#access'] = FALSE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Hide default provided media type by IntelligenceBank from media add page.
 *
 * See @link https://github.com/az-digital/az_quickstart/issues/1741
 */
function az_digital_asset_library_preprocess_entity_add_list(&$variables) {
  if (isset($variables['bundles']) && isset($variables['bundles']['ib_dam_embed'])) {
    unset($variables['bundles']['ib_dam_embed']);
  }
}
