# Schema for the configuration files of the Quickstart Person Profiles Import module.
az_person_profiles_import.settings:
  type: config_object
  label: 'Quickstart Person Profiles Import settings'
  mapping:
    endpoint:
      type: string
      label: 'Profiles Endpoint'
    apikey:
      type: string
      label: 'API Key'
