az_core.settings:
  type: config_object
  label: 'Quickstart Core settings'
  mapping:
    monitoring_page:
      type: mapping
      label: 'Monitoring page'
      mapping:
        enabled:
          type: boolean
          label: 'Monitoring page enabled'
        path:
          type: string
          label: 'Monitoring page path'
    enterprise_attributes:
      type: mapping
      label: 'Enterprise attributes'
      mapping:
        locked:
          type: boolean
          label: 'Enterprise attribute edits prohibited'
    migrations:
      type: mapping
      label: 'Migrations'
      mapping:
        http_cached:
          type: boolean
          label: 'HTTP Fetches Cached'
