<?php

/**
 * @file
 * Contains az_block_types_quick_links.module.
 */

/**
 * Implements hook_preprocess_HOOK().
 *
 * Adds list-group-item classes to field item attributes on field_az_links
 * fields on az_quick_links blocks.
 */
function az_block_types_quick_links_preprocess_field__block_content__field_az_links__az_quick_links(&$variables) {
  $link_classes = [
    'list-group-item',
    'list-group-item-action',
  ];
  foreach ($variables['items'] as $delta => $item) {
    foreach ($link_classes as $class) {
      $variables['items'][$delta]['content']['#options']['attributes']['class'][] = $class;
    }
  }
}
