<?php

/**
 * @file
 * Contains az_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\pathauto\PathautoPatternInterface;
use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\editor\Entity\Editor;

/**
 * Implements hook_help().
 */
function az_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the az_core module.
    case 'help.page.az_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Settings and configuration common to other Quickstart componenets..') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_toolbar().
 */
function az_core_toolbar() {
  $items = [];

  $items['az_quickstart'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Quickstart 2'),
      '#url' => Url::fromRoute('az_core.az_quickstart'),
      '#attributes' => [
        'title' => t('AZ Quickstart 2'),
        'class' => [
          'toolbar-item',
        ],
      ],
    ],
    '#weight' => 101,
  ];

  return $items;
}

/**
 * Implements hook_pathauto_pattern_alter().
 *
 * Provide a fallback if the current node is not in a menu.
 * Reference: https://www.drupal.org/i/2904757#comment-13421490
 */
function az_core_pathauto_pattern_alter(PathautoPatternInterface $pattern, array $context) {
  // Manually specify default AZQS pattern.
  $azqs_pattern = '[node:menu-link:parents:join-path]/[node:menu-link]';

  // Check if context is node and pattern is the AZQS default.
  if ($context['module'] === 'node' && $pattern->getPattern() === $azqs_pattern) {
    $menu = $context['data']['node']->__get('menu');

    // Set pattern to fallback if menu is not enabled.
    if (isset($menu['enabled']) && $menu['enabled'] === 0) {
      $pattern->setPattern('[node:title]');
    }
  }
}

/**
 * Implements hook_modules_installed().
 */
function az_core_modules_installed($modules, $is_syncing) {

  // Import overrides that exist for the enabled modules.
  $overrider = Drupal::service('az_core.override_import');
  if ($overrider) {
    $overrider->importOverrides($modules);
  }
}

/**
 * Implements hook_block_access().
 */
function az_core_block_access(Block $block, $operation, AccountInterface $account) {
  if ($operation === 'view' && $block->id() === 'az_barrio_sidebar_menu') {
    $block_content = \Drupal::entityTypeManager()
      ->getViewBuilder('block')
      ->view($block);
    $markup = \Drupal::service('renderer')->renderRoot($block_content);
    return AccessResult::forbiddenIf($markup === '')->addCacheableDependency($block);
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_ckeditor_css_alter().
 */
function az_core_ckeditor_css_alter(array &$css, Editor $editor) {
  $global_styling = \Drupal::service('library.discovery')->getLibraryByName('az_barrio', 'global-styling');
  if ($global_styling && $global_styling['css']) {
    $css[] = $global_styling['css'][0]['data'];
  };
  $proxima_nova = \Drupal::service('library.discovery')->getLibraryByName('az_barrio', 'az-proxima-nova');
  if ($proxima_nova && $proxima_nova['css']) {
    $css[] = $proxima_nova['css'][0]['data'];
  };
  $arizona_bootstrap = \Drupal::service('library.discovery')->getLibraryByName('az_barrio', 'arizona-bootstrap');
  if ($arizona_bootstrap && $arizona_bootstrap['css']) {
    $css[] = $arizona_bootstrap['css'][0]['data'];
  };
}
