<?php

/**
 * @file
 * Hook implementations and global functions for az_media_trellis.
 */

use Drupal\media\Entity\Media;

/**
 * Implements hook_theme().
 */
function az_media_trellis_theme($existing, $type, $theme, $path) {
  return [
    'az_media_trellis' => [
      'variables' => [
        'type' => NULL,
        'url' => NULL,
        'width' => NULL,
        'height' => NULL,
        'editing' => NULL,
      ],
      'template' => 'az-media-trellis',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for media entities.
 */
function az_media_trellis_preprocess_media(&$variables) {
  // Add a wrapper class to indicate this is a preview.
  // $variables['content']['#prefix'] = '<div class="az-media-trellis-preview">';
  // $variables['content']['#suffix'] = '</div>';.
  // Get the media entity object.
  if (isset($variables['elements']['#media']) && $variables['elements']['#media'] instanceof Media) {
    $media = $variables['elements']['#media'];

    // Check if the current route is an editing context.
    $route_name = \Drupal::routeMatch()->getRouteName();
    $is_editing_context = in_array($route_name, [
    // Node edit form.
      'entity.node.edit_form',
    // Node add form.
      'entity.node.add_form',
    // Media library.
      'media_library.ui',
    // When editing the media inline?
      'media.filter.preview',
    ]);

    \Drupal::logger('az_media_trellis')->info('Current route: @route', ['@route' => \Drupal::routeMatch()->getRouteName()]);
    // Use a custom view mode for editing contexts.
    // Set the 'editing' variable.
    $variables['editing'] = $is_editing_context;
    \Drupal::logger('az_media_trellis')->info('Editing context: @editing', ['@editing' => $variables['editing'] ? 'true' : 'false']);

    // Retrieve the value of the 'field_az_media_trellis_rec_id' field.
    if ($media->hasField('field_az_media_trellis_rec_id') && !$media->get('field_az_media_trellis_rec_id')->isEmpty()) {
      $rec_id_value = $media->get('field_az_media_trellis_rec_id')->value;

      // Pass the value to the JavaScript library via drupalSettings.
      $variables['#attached']['drupalSettings']['azMediaTrellis'] = [
        'tfa_4' => $rec_id_value,
      ];
    }
  }
}
