services:
  config_update.config_diff:
    class: Drupal\config_update\ConfigDiffer
    arguments: ['@string_translation']

  config_update.config_list:
    class: Drupal\config_update\ConfigListerWithProviders
    arguments: ['@entity_type.manager', '@config.storage', '@config_update.extension_storage', '@config_update.extension_optional_storage', '@module_handler', '@theme_handler']

  config_update.config_update:
    class: Drupal\config_update\ConfigReverter
    arguments: ['@entity_type.manager', '@config.storage', '@config_update.extension_storage', '@config_update.extension_optional_storage', '@config.factory', '@event_dispatcher']

  config_update.extension_storage:
    class: Drupal\Core\Config\ExtensionInstallStorage
    arguments: ['@config.storage', 'config/install', '', true, '%install_profile%']

  config_update.extension_optional_storage:
    class: Drupal\Core\Config\ExtensionInstallStorage
    arguments: ['@config.storage', 'config/optional', '', true, '%install_profile%']
