name: devel
type: drupal10
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: [ ]
additional_fqdns: [ ]
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment:
  - SIMPLETEST_DB=mysql://root:root@ddev-devel-db/db
  - SIMPLETEST_BASE_URL=http://ddev-devel-web
