az_eds_user.az_user_role_query.*:
  type: config_entity
  label: Quickstart Role Query Mapping
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    query:
      type: string
    role:
      type: string
