<?php

/**
 * @file
 * Contains az_mail.module.
 */

/**
 * Implements hook_mail_alter().
 */
function az_mail_mail_alter(&$message) {
  $ses_message_tags = [];
  if (isset($_ENV['PANTHEON_SITE_NAME'])) {
    $message['headers']['X-Pantheon-Site-Name'] = $_ENV['PANTHEON_SITE_NAME'];
    $tag = ['key' => 'pantheon-site-name'];
    $tag['value'] = $_ENV['PANTHEON_SITE_NAME'];
    array_push($ses_message_tags, $tag);
  }
  if (isset($_ENV['PANTHEON_SITE'])) {
    $message['headers']['X-Pantheon-Site-Id'] = $_ENV['PANTHEON_SITE'];
    $tag = ['key' => 'pantheon-site-id', 'value' => $_ENV['PANTHEON_SITE']];
    array_push($ses_message_tags, $tag);
  }
  if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
    $message['headers']['X-Pantheon-Environment'] = $_ENV['PANTHEON_ENVIRONMENT'];
    $tag = ['key' => 'pantheon-environment'];
    $tag['value'] = $_ENV['PANTHEON_ENVIRONMENT'];
    array_push($ses_message_tags, $tag);
  }
  if ($smtp_host = \Drupal::config('smtp.settings')->get('smtp_host')) {
    if (preg_match('/email-smtp\..*\.amazonaws.com/', $smtp_host)) {
      if ($configuration_set = \Drupal::config('az_mail.settings')->get('ses_configuration_set')) {
        $message['headers']['X-SES-CONFIGURATION-SET'] = $configuration_set;
      }
      if (count($ses_message_tags) > 0) {
        $message['headers']['X-SES-MESSAGE-TAGS'] = implode(
          ',',
          array_map(
            function ($tag) {
              return $tag['key'] . '=' . $tag['value'];
            },
            $ses_message_tags
          )
        );
      }
    }
  }
}
