<?php

/**
 * @file
 * Install, update and uninstall functions for az_mail module.
 */

/**
 * Implements hook_install().
 */
function az_mail_install() {
  $config_factory = \Drupal::service('config.factory');
  $mail_config = $config_factory->getEditable('system.mail');
  $mail_config->set('interface.default', 'SMTPMailSystem')->save();
}

/**
 * Implements hook_update_last_removed().
 */
function az_mail_update_last_removed() {
  // Remove updates added before 2.6.0.
  return 9201;
}
