<?php

/**
 * @file
 * Contains az_mail.module.
 */

/**
 * Implements hook_mail_alter().
 */
function az_mail_mail_alter(&$message) {
  $ses_message_tags = [];
  if (isset($_ENV['PANTHEON_SITE_NAME'])) {
    $message['headers']['X-Pantheon-Site-Name'] = $_ENV['PANTHEON_SITE_NAME'];
    $tag = ['key' => 'pantheon-site-name', 'value' => $_ENV['PANTHEON_SITE_NAME']];
    array_push($ses_message_tags, $tag);
  }
  if (isset($_ENV['PANTHEON_SITE'])) {
    $message['headers']['X-Pantheon-Site-Id'] = $_ENV['PANTHEON_SITE'];
    $tag = ['key' => 'pantheon-site-id', 'value' => $_ENV['PANTHEON_SITE']];
    array_push($ses_message_tags, $tag);
  }
  if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
    $message['headers']['X-Pantheon-Environment'] = $_ENV['PANTHEON_ENVIRONMENT'];
    $tag = ['key' => 'pantheon-environment', 'value' => $_ENV['PANTHEON_ENVIRONMENT']];
    array_push($ses_message_tags, $tag);
  }
  if ($smtp_host = \Drupal::config('smtp.settings')->get('smtp_host', FALSE)) {
    if (preg_match('/email-smtp\..*\.amazonaws.com/', $smtp_host)) {
      if ($configuration_set = \Drupal::config('az_mail.settings')->get('ses_configuration_set', FALSE)) {
        $message['headers']['X-SES-CONFIGURATION-SET'] = $configuration_set;
      }
      if (count($ses_message_tags) > 0) {
        $message['headers']['X-SES-MESSAGE-TAGS'] = implode(
          ',',
          array_map(
            function ($tag) {
              return $tag['key'] . '=' . $tag['value'];
            },
            $ses_message_tags
          )
        );
      }
    }
  }
}

/**
 * Helper function for az_mail_ses_hash.
 */
function az_mail_ses_sign($key, $msg) {
  return hash_hmac('sha256', utf8_encode($msg), $key, TRUE);
}

/**
 * Derive the SMTP password from the AWS IAM secret key.
 */
function az_mail_ses_hash($secret, $region) {
  // Values that are required to calculate the signature. These values should
  // never change.
  $date = "11111111";
  $service = "ses";
  $message = "SendRawEmail";
  $terminal = "aws4_request";
  $version = 0x04;

  $signature = az_mail_ses_sign(utf8_encode("AWS4" . $secret), $date);
  $signature = az_mail_ses_sign($signature, $region);
  $signature = az_mail_ses_sign($signature, $service);
  $signature = az_mail_ses_sign($signature, $terminal);
  $signature = az_mail_ses_sign($signature, $message);
  $signature_and_version = pack("C*", $version) . $signature;
  $smtp_password = base64_encode($signature_and_version);
  return utf8_decode($smtp_password);
}
