<?php

/**
 * @file
 * Contains az_card.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function az_card_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the az_card module.
    case 'help.page.az_card':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom field plugins and theme template for cards.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function az_card_theme($existing, $type, $theme, $path) {
  return [
    'az_card' => [
      'variables' => [
        'attributes' => [],
        'media' => NULL,
        'title' => NULL,
        'body' => NULL,
        'link' => NULL,
        'link_uri' => NULL,
        'title_style' => 'default',
        'title_alignment' => 'text-left',
        'title_level' => 'h3',
        'title_display' => 'h5',
      ],
      'template' => 'az-card',
    ],
  ];
}
