<?php

/**
 * @file
 * Contains az_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\block_content\BlockContentInterface;

/**
 * Implements hook_help().
 */
function az_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the az_blocks module.
    case 'help.page.az_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom block types.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_block().
 */
function az_blocks_preprocess_block(&$variables) {
  $content = $variables['elements']['content'];

  // Check and see if this is a custom block with content.
  if (isset($content['#block_content']) && $content['#block_content'] instanceof BlockContentInterface) {
    // Find the bundle of the block, e.g. az_accordion and compute library name.
    $bundle = $content['#block_content']->bundle();
    $name = 'az_blocks.' . $bundle;

    // Check to see if az_blocks implements a library matching the block bundle.
    $library = \Drupal::service('library.discovery')->getLibraryByName('az_blocks', $name);

    // If we found a library, attach it to the block.
    if ($library) {
      $variables['#attached']['library'][] = 'az_blocks/' . $name;
    }
  }
}
