<?php

/**
 * @file
 * Contains az_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function az_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the az_blocks module.
    case 'help.page.az_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom block types.') . '</p>';
      return $output;

    default:
  }
}
