/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function (Drupal, once) {
  Drupal.behaviors.azFinderBehavior = {
    attach: function attach(context) {
      console.log('azFinderBehavior attach called');
      once('az-finder-settings', '#az-finder-settings-form-wrapper', context).forEach(function (element) {
        console.log('az-finder-settings found');
        element.addEventListener('click', function (event) {
          console.log('Wrapper clicked');
          if (event.target && event.target.name === 'op' && event.target.value === 'Add Override') {
            console.log('Add Override button clicked.');
          }
        });
      });
    }
  };
})(Drupal, once);