smtp_on: true
smtp_host: email-smtp.us-west-2.amazonaws.com
smtp_hostbackup: ''
smtp_port: '2587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 30
smtp_username: ''
smtp_password: ''
smtp_from: ''
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
smtp_keepalive: false
