spambot_whitelist_email: ''
spambot_whitelist_username: ''
spambot_whitelist_ip: ''
spambot_whitelist_email_list: {  }
spambot_whitelist_username_list: {  }
spambot_whitelist_ip_list: {  }
spambot_user_register_protect: true
spambot_check_blocked_accounts: false
spambot_log_blocked_registration: true
spambot_sfs_api_key: ''
spambot_blocked_message: false
spambot_cron_user_limit: 0
spambot_spam_account_action: 0
spambot_criteria_email: 1
spambot_criteria_username: 0
spambot_criteria_ip: 20
spambot_blacklisted_delay: 20
spambot_blocked_message_email: 'Forbidden'
spambot_blocked_message_username: 'Forbidden'
spambot_blocked_message_ip: 'Forbidden'
spambot_enable_cache: 1
spambot_cache_expire: -1
spambot_cache_expire_false: -1
