<?php

/**
 * @file
 * Contains az_marketing_cloud.module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_theme().
 */
function az_marketing_cloud_theme($existing, $type, $theme, $path) {
  return [
    'node__view__az_marketing_cloud__30_70_layout' => [
      'template' => 'node--view--az-marketing-cloud--30-70-layout',
      'base hook' => 'node',
    ],
    'node__view__az_marketing_cloud__50_50_layout' => [
      'template' => 'node--view--az-marketing-cloud--50-50-layout',
      'base hook' => 'node',
    ],
    'node__view__az_marketing_cloud__text_layout' => [
      'template' => 'node--view--az-marketing-cloud--text-layout',
      'base hook' => 'node',
    ],
    'page__export__marketing_cloud' => [
      'template' => 'page--export--marketing-cloud',
      'base hook' => 'page',
    ],
    'html__export__marketing_cloud' => [
      'template' => 'html--export--marketing-cloud',
      'base hook' => 'html',
    ],
    'block__az_barrio_page_title' => [
      'template' => 'block--az-barrio-page-title',
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function az_marketing_cloud_preprocess_node__view__az_marketing_cloud(&$variables) {
  $node = $variables['node'];
  if ($node->getType() === 'az_news') {
    $token_service = \Drupal::token();
    $bubbleable_metadata = new BubbleableMetadata();
    // Find the root URL.
    $base = \Drupal::request()->getSchemeAndHttpHost();
    $canonical_url = $token_service->replace('[node:az-canonical-url]', ['node' => $node], [], $bubbleable_metadata);
    $variables['az_canonical_url'] = Html::transformRootRelativeUrlsToAbsolute($canonical_url, $base);
    $variables['az_canonical_summary_link_title'] = $token_service->replace('[node:az-canonical-summary-link-title]', ['node' => $node], [], $bubbleable_metadata);
    $media = $node->field_az_media_image->entity ?? NULL;
    $file = $media->field_media_az_image->entity ?? NULL;
    if (!empty($file)) {
      $uri = $file->getFileUri();
      $styles = [
        'az_marketing_cloud_30_70_layout',
        'az_marketing_cloud_50_50_layout',
      ];
      foreach ($styles as $style) {
        $image_style = ImageStyle::load($style);
        if (!empty($image_style)) {
          $variables['images'][$style] = $image_style->buildUrl($uri);
        }
      }
    }
  }
}

/**
 * Implements template_preprocess_views_view().
 */
function az_marketing_cloud_preprocess_views_view(&$variables) {
  $view = $variables['view'];

  if ($view->id() === 'az_marketing_cloud') {
    $variables['#attached']['library'][] = 'az_marketing_cloud/admin';
  }
}
