<?php

/**
 * @file
 * Contains az_enterprise_attributes_import.module.
 */

/**
 * Implements hook_migration_plugins_alter().
 */
function az_enterprise_attributes_import_migration_plugins_alter(array &$migrations) {

  if (!empty($migrations['az_enterprise_attributes_import'])) {
    $endpoint = \Drupal::config('az_enterprise_attributes_import.settings')->get('endpoint');
    if (!empty($endpoint)) {
      $migrations['az_enterprise_attributes_import']['source']['urls'] = [$endpoint];
    }
  }
}
