<?php

/**
 * @file
 * Contains az_paragraphs_text_media.module.
 */

/**
 * Implements hook_theme().
 */
function az_paragraphs_text_media_theme($existing, $type, $theme, $path): array {
  return [
    'field__paragraph__az_text_media' => [
      'template' => 'field--paragraph--az-text-media',
      'base hook' => 'field',
    ],
  ];
}

// /**
//  * Implements hook_field_group_pre_render_alter().
//  */
// function az_paragraphs_text_media_field_group_pre_render_alter(array &$element, &$group, &$rendering_object) {
//   if (array_key_exists('#paragraph', $rendering_object)) {
//     if ($rendering_object['#paragraph']->bundle() === 'az_text_media') {
//       $paragraph = $rendering_object['#paragraph'];
//       $full_width = $paragraph->getBehaviorSetting('az_text_media_paragraph_behavior', 'full_width', $default = NULL);
//       $text_bottom_spacing = $paragraph->getBehaviorSetting('az_text_media_paragraph_behavior', 'text_media_spacing', $default = NULL);
//       if ($text_bottom_spacing === 'aspect-ratio' && $full_width === 'full-width-background') {
//         if ($group->group_name === 'group_az_container') {
//           dpm($group);

//           $element['#theme_wrappers'] = [
//             'container' => [
//               '#attributes' => [
//                 'class' => [
//                   'container-absolute',
//                   'align-items-center',
//                   'd-flex',
//                 ],
//               ],
//             ],
//           ];
//         }
//       }
//       if ($group->group_name === 'group_az_full_width_row') {
//         // dpm($element['#theme_wrappers']['container']['#attributes']['class']);
//         // if (!is_array($element['#theme_wrappers']['container']['#attributes'])) {
//         //   $element['#theme_wrappers']['container']['#attributes']['class'] = ['h-100'];
//         // }
//         // else {
//           $element['#theme_wrappers']['container']['#attributes']['class'][] = 'h-100';
//         // }

//       }
//       if ($group->group_name === 'group_az_content') {
//         // if (!is_array($element['#theme_wrappers']['container']['#attributes'])) {
//         //   $element['#theme_wrappers']['container']['#attributes']['class'][] = 'h-100';
//         // }
//         // else {
//         //   $element['#theme_wrappers']['container']['#attributes']['class'][] = 'h-100';
//         // }
//       }
//     }
//   }
// }
