<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('variable', array(
  'fields' => array(
    'name' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ),
    'value' => array(
      'type' => 'blob',
      'not null' => TRUE,
      'size' => 'big',
    ),
  ),
  'primary key' => array(
    'name',
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('variable')
->fields(array(
  'name',
  'value',
))
->values(array(
  'name' => 'chosen_allow_single_deselect',
  'value' => 'i:1;',
))
->values(array(
  'name' => 'chosen_disabled_themes',
  'value' => 'a:2:{s:6:"bartik";i:0;s:5:"seven";i:0;}',
))
->values(array(
  'name' => 'chosen_disable_search',
  'value' => 'i:0;',
))
->values(array(
  'name' => 'chosen_disable_search_threshold',
  'value' => 's:1:"0";',
))
->values(array(
  'name' => 'chosen_include',
  'value' => 's:1:"2";',
))
->values(array(
  'name' => 'chosen_jquery_selector',
  'value' => 's:14:"select:visible";',
))
->values(array(
  'name' => 'chosen_minimum_multiple',
  'value' => 's:1:"0";',
))
->values(array(
  'name' => 'chosen_minimum_single',
  'value' => 's:1:"0";',
))
->values(array(
  'name' => 'chosen_minimum_width',
  'value' => 's:3:"200";',
))
->values(array(
  'name' => 'chosen_no_results_text',
  'value' => 's:16:"No results match";',
))
->values(array(
  'name' => 'chosen_placeholder_text_multiple',
  'value' => 's:19:"Choose some options";',
))
->values(array(
  'name' => 'chosen_placeholder_text_single',
  'value' => 's:16:"Choose an option";',
))
->values(array(
  'name' => 'chosen_search_contains',
  'value' => 'i:1;',
))
->execute();
