<?php

namespace Drupal\az_search_api\Plugin\search_api\processor\Property;

use Drupal\search_api\Processor\ProcessorProperty;

/**
 * Property for autogenerated summaries.
 */
class AZSummaryProperty extends ProcessorProperty {

}
