/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  Drupal.behaviors.azParagraphsPushSidebarDown = {
    attach: function attach() {
      function _calculateParagraphHeight() {
        var content_region = document.getElementById('content');
        var sidebar_pusher = document.querySelectorAll('[push-sidebar-down="push-sidebar-down"]');
        console.log(sidebar_pusher[0]);
        var content_region_position = content_region.getBoundingClientRect();
        var content_region_top = content_region_position.top;
        var sidebar_pusher_position = sidebar_pusher[0].getBoundingClientRect();
        var sidebar_pusher_bottom = sidebar_pusher_position.bottom;
        var sidebar_top_margin = sidebar_pusher_bottom - content_region_top;
        document.documentElement.style.setProperty("--sidebar-top-margin", "".concat(sidebar_top_margin, "px"));
      }

      window.addEventListener("resize", _calculateParagraphHeight, false);
      document.addEventListener("DOMContentLoaded", _calculateParagraphHeight, false);
      window.addEventListener("load", _calculateParagraphHeight);
    }
  };
})(Drupal);