/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.azParagraphsFullWidth = {
    attach: function attach() {
      function _calculateScrollbarWidth() {
        document.documentElement.style.setProperty("--scrollbar-width", "".concat(window.innerWidth - document.documentElement.clientWidth, "px"));
      }

      window.addEventListener("resize", _calculateScrollbarWidth, false);
      window.addEventListener("DOMContentLoaded", function (event) {
        _calculateScrollbarWidth();
      });
      window.addEventListener("load", _calculateScrollbarWidth);
    }
  };
})(jQuery, Drupal);