/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
document.addEventListener('DOMContentLoaded', function () {
  document.querySelectorAll('.az-gallery-modal').forEach(function (modal) {
    var carousel = modal.querySelector('.carousel.az-gallery');
    if (!carousel) return;
    var prevBtn = carousel.querySelector('.carousel-control-prev');
    var nextBtn = carousel.querySelector('.carousel-control-next');
    var items = carousel.querySelectorAll('.carousel-item');
    var updateNavButtons = function updateNavButtons() {
      prevBtn.disabled = false;
      nextBtn.disabled = false;
      prevBtn.querySelector('.visually-hidden').textContent = 'Previous';
      nextBtn.querySelector('.visually-hidden').textContent = 'Next';
    };
    carousel.addEventListener('slid.bs.carousel', updateNavButtons);
    modal.addEventListener('shown.bs.modal', function () {
      setTimeout(updateNavButtons, 50);
    });
    function setActiveSlide(targetIndex) {
      items.forEach(function (item, index) {
        if (index === targetIndex) {
          item.classList.add('active');
        } else {
          item.classList.remove('active');
        }
      });
      var indicators = carousel.querySelectorAll('.carousel-indicators button');
      indicators.forEach(function (indicator, index) {
        if (index === targetIndex) {
          indicator.classList.add('active');
          indicator.setAttribute('aria-current', 'true');
        } else {
          indicator.classList.remove('active');
          indicator.removeAttribute('aria-current');
        }
      });
      updateNavButtons();
    }
    document.querySelectorAll(".az-gallery-open-modal[data-bs-target=\"#".concat(modal.id, "\"]")).forEach(function (thumbnail) {
      thumbnail.addEventListener('mousedown', function () {
        var slideIndex = thumbnail.getAttribute('data-bs-slide-to');
        setActiveSlide(parseInt(slideIndex, 10));
      });
      thumbnail.addEventListener('keydown', function (e) {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          var slideIndex = thumbnail.getAttribute('data-bs-slide-to');
          setActiveSlide(parseInt(slideIndex, 10));
          thumbnail.click();
        }
      });
    });
    modal.addEventListener('shown.bs.modal', function () {
      updateNavButtons();
    });
    updateNavButtons();
  });
});