/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
document.addEventListener('DOMContentLoaded', function () {
  document.querySelectorAll('.az-gallery-modal').forEach(function (modal) {
    var carousel = modal.querySelector('.carousel.az-gallery');
    if (!carousel) return;
    var prevBtn = carousel.querySelector('.carousel-control-prev');
    var nextBtn = carousel.querySelector('.carousel-control-next');
    var items = carousel.querySelectorAll('.carousel-item');
    var updateNavButtons = function updateNavButtons() {
      var activeIndex = Array.from(items).findIndex(function (item) {
        return item.classList.contains('active');
      });
      prevBtn.disabled = activeIndex === 0;
      nextBtn.disabled = activeIndex === items.length - 1;
      prevBtn.querySelector('.visually-hidden').textContent = activeIndex === 0 ? 'No previous slide' : 'Previous';
      nextBtn.querySelector('.visually-hidden').textContent = activeIndex === items.length - 1 ? 'Return to first slide' : 'Next';
    };
    carousel.addEventListener('slid.bs.carousel', updateNavButtons);
    modal.addEventListener('shown.bs.modal', function () {
      setTimeout(updateNavButtons, 50);
    });
    var requestedSlideIndex = null;
    document.querySelectorAll(".az-gallery-open-modal[data-bs-target=\"#".concat(modal.id, "\"]")).forEach(function (thumbnail) {
      thumbnail.addEventListener('mousedown', function () {
        requestedSlideIndex = this.getAttribute('data-bs-slide-to');
      });
      thumbnail.addEventListener('keydown', function (e) {
        if (e.key === 'Enter' || e.key === ' ') {
          requestedSlideIndex = this.getAttribute('data-bs-slide-to');
        }
      });
    });
    modal.addEventListener('shown.bs.modal', function () {
      if (requestedSlideIndex !== null) {
        var indicator = carousel.querySelector(".carousel-indicators [data-bs-slide-to=\"".concat(requestedSlideIndex, "\"]"));
        if (indicator) {
          indicator.click();
        }
        requestedSlideIndex = null;
      }
    });
    updateNavButtons();
  });
});