/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
((Drupal, once) => {
  Drupal.behaviors.azRankingsParagraphBehavior = {
    attach: context => {
      const clickableCheckboxes = once('az-rankings-clickable', 'input[name*="[ranking_clickable]"]', context);
      clickableCheckboxes.forEach(clickableElement => {
        const clickableName = clickableElement.getAttribute('name');
        const hoverEffectName = clickableName.replace('[ranking_clickable]', '[ranking_hover_effect]');
        const hoverEffectElement = document.querySelector(`input[name="${hoverEffectName}"]`);
        if (!hoverEffectElement) {
          return;
        }
        clickableElement.addEventListener('change', () => {
          if (!clickableElement.checked) {
            if (hoverEffectElement.checked) {
              hoverEffectElement.checked = false;
              hoverEffectElement.dispatchEvent(new Event('change', {
                bubbles: true
              }));
            }
          }
        });
      });
    }
  };
})(Drupal, once);