<?php

/**
 * Implements hook_preprocess_html().
 */
function upgrade_status_test_library_preprocess_html(&$variables) {
  $variables['#attach']['libraries'] = [
    'upgrade_status_test_library/deprecated_library',
  ];
  $variables['#attach']['libraries'][] = 'upgrade_status_test_twig/deprecated_library';

  // These should be skipped.
  $library = 'deprecated_library';
  $variables['#attach']['libraries'][] = "upgrade_status_test_library/$library";
}
