az_gdpr_consent.settings:
  type: config_object
  label: 'Quickstart GDPR Consent Management settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable geolocation-based consent management'
    target_countries:
      type: sequence
      label: 'Target country codes'
      sequence:
        type: string
        label: 'Country code'
    show_on_unknown_location:
      type: boolean
      label: 'Show consent banner when location is unknown'
    test_mode:
      type: boolean
      label: 'Test mode'
