<?php

/**
 * @file
 * Contains az_news.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Component\Utility\Html;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function az_news_theme($existing, $type, $theme, $path) {
  return [
    'field__node__az_news' => [
      'template' => 'field--node--az-news',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function az_news_entity_extra_field_info() {
  $extra = [];

  // Check to see if our content type exists.
  $bundle = NodeType::load('az_news');
  if ($bundle) {
    // Link title pseudo field.
    $extra['node'][$bundle->id()]['display']['az_news_read_more'] = [
      'label' => t('Read more pseudo link.'),
      'description' => "This is a pseudo field from az_news",
      'weight' => 50,
      'visible' => FALSE,
    ];
  }

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function az_news_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  if ($entity instanceof FieldableEntityInterface && $entity->hasField('field_az_link')) {
    $bubbleable_metadata = new BubbleableMetadata();
    // Read more pseudo field.
    if ($display->getComponent('az_news_read_more')) {
      $build['az_news_read_more'][] = [
        '#type' => 'markup',
        '#markup' => Html::escape(\Drupal::service('token')
          ->replace('[node:az-canonical-summary-link-title]', [
            'node' => $entity,
          ], [], $bubbleable_metadata)),
      ];
    }
    $bubbleable_metadata->applyTo($build);
  }

}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Sets the Thumbnail Image field to match the Photo field in two cases where
 * we can assume a user hasn't set the thumbnail to a specific image.
 */
function az_news_node_presave(EntityInterface $entity) {
  if ($entity->bundle() === 'az_news' && $entity instanceof NodeInterface) {
    if (isset($entity->field_az_media_image->entity)) {
      if (
        // First case: set the Thumbnail Image field if it is empty.
        !isset($entity->field_az_media_thumbnail_image->entity)
        || (
          // Second case: set the Thumbnail Image field if the two image fields
          // were the same originally, but are now different after a user
          // changed only the Photo field.
          $entity->original instanceof NodeInterface
          && $entity->original->field_az_media_image->target_id === $entity->original->field_az_media_thumbnail_image->target_id
          && $entity->field_az_media_image->target_id !== $entity->original->field_az_media_image->target_id
        )
      ) {
        $entity->field_az_media_thumbnail_image->target_id = $entity->field_az_media_image->target_id;
        // @todo Remove message below before merging.
        \Drupal::messenger()->addStatus(t('%title - Set thumbnail image to match main image (media ID %thumb). This message will be removed before this PR is merged.',
          [
            '%title' => $entity->getTitle(),
            '%thumb' => $entity->field_az_media_thumbnail_image->target_id,
          ]));
      }
    }
  }
}
