<?php

/**
 * @file
 * Contains az_finder.module.
 */

/**
 * Implements hook_theme().
 */
function az_finder_theme($existing, $type, $theme, $path) {
  return [
    'az_finder_widget' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for az_finder_widget.
 */
function template_preprocess_az_finder_widget(&$variables) {
  // Check if the class exists.
  if (class_exists('\Drupal\az_finder\Plugin\better_exposed_filters\filter\AzFinderWidget')) {
    // Create an instance of the AzFinderWidget class.
    $widget = \Drupal::service('plugin.manager.better_exposed_filters_filter_widget')
      ->createInstance('az_finder', []);
    // Call the preprocessAzFinderWidget method with the variables.
    try {
      $widget->preprocessAzFinderWidget($variables);
    }
    catch (\Exception $e) {
      // Log any errors.
      \Drupal::logger('az_finder')->error('Error in preprocessAzFinderWidget: @message', ['@message' => $e->getMessage()]);
    }
  }
}
