name: 'Basic shortcuts'
description: 'Provides a basic set of shortcuts for logged-in users.'
type: Administration
install:
  - shortcut
config:
  import:
    shortcut:
      - shortcut.set.default
  actions:
    user.role.authenticated:
      grantPermission: 'access shortcuts'
