<?php

/**
 * @file
 * common.inc
 *
 * Contains common functionality for the entire theme.
 */
// @deprecated AZ_BOOTSTRAP_STABLE_VERSION will be removed in version 2.9.0 in
// favor of Drupal/az_core/AzLibraryVersionChecker::getSemanticInstalledVersion().
define('AZ_BOOTSTRAP_STABLE_VERSION', '2.0.24');
// @deprecated AZ_BOOTSTRAP_STABLE_VERSION will be removed in version 2.9.0 in
// favor of Drupal/az_core/AzLibraryVersionChecker::getSemanticInstalledVersion().
define('AZ_ICONS_STABLE_VERSION', 'main');

/**
 * Persistent variable name for exporting the AZ Bootstrap CSS location.
 */
// @deprecated AZ_BOOTSTRAP_LOCATION will be removed in version 2.9.0, there is
// no need for this anymore, use the library API instead.
 const AZ_BOOTSTRAP_LOCATION = 'az_bootstrap_location';

