<?php

/**
 * @file
 * Contains az_paragraphs_stats.module.
 */

use Drupal\paragraphs\ParagraphInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_field_group_pre_render_alter().
 */
function az_paragraphs_stats_field_group_pre_render_alter(array &$element, &$group, &$rendering_object) {

  // Special rules for rendering the paragraph title.
  if (($group->group_name === 'group_title') && !empty($rendering_object['#paragraph'])) {
    $paragraph = $rendering_object['#paragraph'];
    // Make sure we have a paragraph entity.
    if ($paragraph instanceof ParagraphInterface) {
      // Only run for stats.
      if ($paragraph->bundle() === 'az_stats') {
        // Get the behavior settings.
        $settings = $paragraph->getAllBehaviorSettings();
        $stat_settings = $settings['az_stats_paragraph_behavior'] ?? [];
        // If we have a color, apply it to the field group.
        if (!empty($stat_settings['stat_deck_title_color'])) {
          if (!empty($element['#attributes']) && ($element['#attributes'] instanceof Attribute)) {
            $element['#attributes']->addClass($stat_settings['stat_deck_title_color']);
          }
        }
      }
    }
  }
}
