#!/bin/sh

## Description: Provide drupal-check tooling to check for deprecated custom code.
## Usage: drupal-check [flags] [args]
## Example: "ddev drupal-check --version"

vendor/bin/drupal-check web/profiles web/modules web/themes $@
