#!/bin/bash

## Description: Run eslint inside the web container
## Usage: eslint [args]
## Example: "eslint" or "eslint myfile.js" or "eslint ."

cd /usr/local/quickstart-install-profile && yarn run eslint $@
