#!/bin/sh

## Description: Provide phpcs tooling to check coding standards.
## Usage: phpcs [flags] [args]
## Example: "ddev phpcs --version"

vendor/bin/phpcs --colors web/profiles/custom/az_quickstart $@
