#!/bin/bash

## Description: Provide phpstan tooling to check for code quality and deprecated code.
## Usage: phpstan [flags] [args]
## Example: "ddev phpstan --version"

vendor/bin/phpstan --configuration=/var/www/html/web/profiles/custom/az_quickstart/phpstan.neon -- /var/www/html/web/profiles/custom/az_quickstart $@
