#!/bin/sh

## Description: Provide phpstan tooling to check for deprecated contrib module/theme code.
## Usage: phpstan [flags] [args]
## Example: "ddev phpstan --version"

vendor/bin/phpstan --configuration web/profiles/custom/az_quickstart/phpstan.neon web/modules web/themes $@
