#!/bin/bash

## Description: Provide phpstan tooling to check for deprecated contrib module/theme code.
## Usage: phpstan-contrib [flags] [args]
## Example: "ddev phpstan-contrib --version"

vendor/bin/phpstan --configuration web/profiles/custom/az_quickstart/phpstan-contrib.neon web/modules web/themes $@
