#!/bin/bash

## Description: Run all PHPUnit tests in parallel via Fastest.
## Usage: phpunit-fastest
## Example: "ddev phpunit-fastest"

find web/profiles/custom/az_quickstart/ -name "*Test.php" | vendor/bin/fastest -vvv "vendor/bin/phpunit {} --configuration /var/www/html/web/profiles/custom/az_quickstart/phpunit.xml.dist --bootstrap /var/www/html/web/core/tests/bootstrap.php;"
