#!/bin/sh

## Description: Enable theme debugging.
## Usage: theme-debug
## Example: "ddev theme-debug"

echo "theme-debug relied on Drupal console (now deprecated) and is no longer availabe.  Please consult the README for instructions on how to manually turn on Twig debug and other debugging settings."
