#!/bin/sh

## Description: Enable theme debugging.
## Usage: theme-debug [args]
## Example: "ddev theme-debug MODE"

if [ $# -eq 0 ]; then
    echo "Usage: ddev theme-debug MODE"
    exit 0
fi

if [[ $* = 'off' ]]; then
  MODE="off"
else
  MODE="on"
fi

drush twig:debug ${MODE}
