<?php

/**
 * @file
 * Contains az_event.module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function az_event_theme($existing, $type, $theme, $path) {
  return [
    'field__node__az_event' => [
      'template' => 'field--node--az-event',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function az_event_entity_extra_field_info() {
  $extra = [];

  // Check to see if our content type exists.
  $bundle = NodeType::load('az_event');
  if ($bundle) {
    // Month pseudo field.
    $extra['node'][$bundle->id()]['display']['az_event_month'] = [
      'label' => t('Event Month'),
      'description' => "This is a pseudo field from az_event.",
      'weight' => 50,
      'visible' => FALSE,
    ];

    // Day pseudo field.
    $extra['node'][$bundle->id()]['display']['az_event_day'] = [
      'label' => t('Event Day'),
      'description' => "This is a pseudo field from az_event.",
      'weight' => 50,
      'visible' => FALSE,
    ];
  }

  return $extra;
}

/**
 * Implements hook_preprocess_field().
 */
function az_event_preprocess_field(&$variables, $hook) {
  $element = $variables['element'];
  if ($element['#field_name'] === 'field_az_event_category') {
    foreach ($variables['items'] as $key => $item) {
      $variables['items'][$key]['content']['#options']['attributes']['class'][] = 'badge badge-link badge-light float-left mr-2 mb-2';
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function az_event_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  // We only know what to do with event pseudo fields if our date seems defined.
  if ($entity instanceof FieldableEntityInterface && $entity->hasField('field_az_event_date') && !empty($entity->field_az_event_date->value)) {
    $timestamp = $entity->field_az_event_date->value;
    $formatter = \Drupal::service('date.formatter');

    // Use the date.formatter service.
    if ($formatter) {
      // Month pseudo field.
      if ($display->getComponent('az_event_month')) {
        $build['az_event_month'][] = [
          '#type' => 'markup',
          '#markup' => Html::escape($formatter->format($timestamp, 'az_event_month')),
        ];
      }

      // Day pseudo field.
      if ($display->getComponent('az_event_day')) {
        $build['az_event_day'][] = [
          '#type' => 'markup',
          '#markup' => Html::escape($formatter->format($timestamp, 'az_event_day')),
        ];
      }
    }
  }

}

/**
 * Implements hook_preprocess_node().
 */
function az_event_preprocess_node(&$variables) {

  $node = $variables['node'];

  // Only for the event content type.
  if ($node->getType() === 'az_event') {

    // Only process if we see view information.
    if (isset($variables['elements']['#az_view_row_index'])) {

      // Get row and delta for transformations.
      $row_index = $variables['elements']['#az_view_row_index'];
      $delta = (int) $node->view->result[$row_index]->node__field_az_event_date_delta;

      // There is a field value at our computed delta.
      if (!empty($variables['content']['field_az_event_date'][$delta])) {
        $all_children = Element::children($variables['content']['field_az_event_date']);
        foreach ($all_children as $child) {
          if ($child !== $delta) {
            // Hide all the others.
            $variables['content']['field_az_event_date'][$child]['#access'] = FALSE;
          }
        }

        // Transform the sidebar psuedofields if needed.
        if ($node->hasField('field_az_event_date')) {
          $values = $node->get('field_az_event_date')->getValue();
          if (!empty($values[$delta]['value'])) {
            $timestamp = $values[$delta]['value'];
            $formatter = \Drupal::service('date.formatter');

            // Format the replacement value.
            if (!empty($variables['content']['az_event_day'])) {
              $variables['content']['az_event_day'][0]['#markup'] = Html::escape($formatter->format($timestamp, 'az_event_day'));
              $variables['content']['az_event_day']['#cache']['max-age'] = 0;
            }
            if (!empty($variables['content']['az_event_month'])) {
              $variables['content']['az_event_month']['#cache']['max-age'] = 0;
              $variables['content']['az_event_month'][0]['#markup'] = Html::escape($formatter->format($timestamp, 'az_event_month'));
            }
          }
        }
      }
      // Don't cache this particular field.
      $variables['content']['field_az_event_date']['#cache']['max-age'] = 0;
    }
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function az_event_preprocess_views_view(&$variables) {

  // EntityRow views do not give the entity access to a row_index.
  // We need to provide one to understand the delta relationship
  // of the row.
  if ($variables['id'] === 'az_events') {
    if (!empty($variables['rows'][0]['#rows'])) {
      foreach ($variables['rows'][0]['#rows'] as $i => $n) {
        $variables['rows'][0]['#rows'][$i]['#az_view_row_index'] = $i;
      }
    }
  }

}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Hide the event view category search if there are no options.
 */
function az_event_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $view = $form_state->get('view');
  if (($view->id() === 'az_events') && ($view->current_display === 'page_1')) {

    // Check to see if the event category filter seems to exist in this display.
    if (isset($form['term_node_tid_depth'])) {
      if (isset($form['term_node_tid_depth']['#options']) &&
        is_array($form['term_node_tid_depth']['#options'])) {
        // We will only show the category filter in some cases.
        $keep_filter = TRUE;

        // Get the arguments statically, as this hook is called multiple times.
        // At some points in the request, the arguments disappear.
        $view_args = &drupal_static(__FUNCTION__);
        if (!isset($view_args)) {
          $view_args = $view->args;
        }

        // Check if our event category filter doesn't contain multiple terms.
        // The implication is this site probably doesn't use this vocabulary.
        if (count($form['term_node_tid_depth']['#options']) <= 1) {
          $keep_filter = FALSE;
        }

        // Check if we seem to have contextual filter arguments.
        if (isset($view_args) && is_array($view_args) && !empty($view_args)) {
          $keep_filter = FALSE;
        }

        // Hide the category filter if either of the above were the case.
        // Our goal is to hide the filter if it conflicts or has no terms.
        if (!$keep_filter) {
          $form['term_node_tid_depth']['#access'] = FALSE;
        }
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Sets the Thumbnail Image field to match the first item of the
 * "Featured Images" field if the Use Featured Image as Thumbnail
 * checkbox is checked.
 */
function az_event_node_presave(EntityInterface $entity) {
  if ($entity->bundle() === 'az_event'
    && $entity instanceof NodeInterface
    && !empty($entity->get('field_az_featured_image_as_thumb')->getValue()[0]['value'])) {
    $entity->get('field_az_media_thumbnail_image')->target_id = $entity->get('field_az_photos')->target_id;
  }
}
