<?php

/**
 * @file
 * Module that implements all the hook from Config Ignore for testing purposes.
 */

/**
 * Implements hook_config_ignore_settings_alter().
 */
function config_ignore_hook_test_config_ignore_settings_alter(array &$settings) {
  $settings[] = 'system.site';

  $count = \Drupal::state()->get('hook_config_ignore_settings_alter__call_count', 0);
  \Drupal::state()->set('hook_config_ignore_settings_alter__call_count', $count + 1);
}
