<?php

/**
 * @file
 * Contains az_paragraphs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function az_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the az_paragraphs module.
    case 'help.page.az_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides custom paragraph types.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function az_paragraphs_theme_registry_alter(&$theme_registry) {
  if ($theme_registry['field_multiple_value_form']) {
    if (isset($theme_registry['field_multiple_value_form']['preprocess functions'])) {
      $key = array_search('paragraphs_preprocess_field_multiple_value_form', $theme_registry['field_multiple_value_form']['preprocess functions'], TRUE);
      unset($theme_registry['field_multiple_value_form']['preprocess functions'][$key]);
      $theme_registry['field_multiple_value_form']['preprocess functions'][] = 'paragraphs_preprocess_field_multiple_value_form';
    }
  }

  $module_path = \Drupal::service('extension.list.module')->getPath('az_paragraphs');
  // Find all .html.twig files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.html.twig', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || strpos($theme_registry[$key]['theme path'], 'themes/') === FALSE) {
      // Copy default paragraph registry entry for paragraph entries.
      if (strpos($key, 'paragraph__') === 0) {
        $theme_registry[$key] = $theme_registry['paragraph'];
      }
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

/**
 * Implements hook_library_info_alter().
 *
 * Alter path of CKE5 anchor link library to match the one installed by 
 * composer.
 * @link https://www.drupal.org/project/anchor_link/issues/3406349#comment-15463373
 */
function az_paragraphs_library_info_alter(&$libraries, $extension) {
  if ($extension === 'anchor_link' && isset($libraries['cke5_anchor_link'])) {
    $libraries['cke5_anchor_link']['js'] = [
      '/libraries/northernco--ckeditor5-anchor-drupal/build/anchor-drupal.js' => [
        'preprocess' => FALSE,
        'minified' => TRUE,
      ],
    ];
  }
}
