id: d6_contact_settings
label: Contact configuration
migration_tags:
  - Drupal 6
  - Configuration
source:
  plugin: contact_settings
  variables:
    - contact_default_status
    - contact_hourly_threshold
process:
  user_default_enabled: contact_default_status
  'flood/limit': contact_hourly_threshold
  'flood/interval':
    plugin: default_value
    # It was defaulted to 3600 in D6.
    # @see https://api.drupal.org/api/drupal/includes%21common.inc/function/flood_is_allowed/6.x
    default_value: 3600
  default_form:
    plugin: migration_lookup
    migration: contact_category
    source: default_category
destination:
  plugin: config
  config_name: contact.settings
migration_dependencies:
  required:
    - contact_category
