metatag.metatag_tag.schema_college_or_university_name:
  type: text
  label: 'name'

metatag.metatag_tag.schema_college_or_university_description:
  type: text_long
  label: 'description'

metatag.metatag_tag.schema_college_or_university_url:
  type: url
  label: 'url'

metatag.metatag_tag.schema_college_or_university_address:
  type: text
  label: 'address'

metatag.metatag_tag.schema_college_or_university_email:
  type: text
  label: 'email'

metatag.metatag_tag.schema_college_or_university_telephone:
  type: text
  label: 'telephone'

metatag.metatag_tag.schema_college_or_university_image:
  type: image
  label: 'image'

metatag.metatag_tag.schema_college_or_university_logo:
  type: image
  label: 'logo'

metatag.metatag_tag.schema_college_or_university_parent_organization:
  type: organization
  label: 'parent_organization'

metatag.metatag_tag.schema_college_or_university_same_as:
  type: url
  label: 'same_as'


