<?php

/**
 * @file
 * Contains metatag_google_cse.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_help().
 */
function metatag_google_cse_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the metatag_google_cse module.
    case 'help.page.metatag_google_cse':
      $output = '';
      $output .= '<h3>' . (string) new TranslatableMarkup('About') . '</h3>';
      $output .= '<p>' . (string) new TranslatableMarkup('Provides support for meta tags used for Google Custom Search Engine.') . '</p>';
      return $output;

    default:
  }
}
