<?php

/**
 * @file
 * Contains az_content_chunks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function az_content_chunks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the az_content_chunks module.
    case 'help.page.az_content_chunks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides custom paragraph types.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function az_content_chunks_preprocess_paragraph(&$variables) {

  // Apply paragraph preprocessing.
  \Drupal::service('az_content_chunks.paragraph_customizations')->preprocessParagraph($variables);

}
