# Recipe for AZ Quickstart local development
type: php
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm

# Default application ports
router_http_port: "80"
router_https_port: "443"

# Optional, enable for greater windows performance
nfs_mount_enabled: false

# Other configuration
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.11"
provider: default
use_dns_when_possible: true
timezone: ""

web_environment:
  - BROWSERTEST_OUTPUT_DIRECTORY=/tmp
  - BROWSERTEST_OUTPUT_BASE_URL=${DDEV_PRIMARY_URL}
  - SIMPLETEST_BASE_URL=http://web
  - SIMPLETEST_DB=mysql://db:db@db/db
  # Use disable-dev-shm-usage instead of setting shm_usage
  # https://developers.google.com/web/tools/puppeteer/troubleshooting#tips
  # The format of chromeOptions is defined at https://chromedriver.chromium.org/capabilities
  - MINK_DRIVER_ARGS_WEBDRIVER=[\"chrome\", {\"browserName\":\"chrome\",\"goog:chromeOptions\":{\"w3c\":false,\"args\":[\"--disable-gpu\",\"--headless\", \"--no-sandbox\", \"--disable-dev-shm-usage\"]}}, \"http://selenium-chrome:4444/wd/hub\"]
  # Nightwatch
  - DRUPAL_TEST_BASE_URL=http://web
  - DRUPAL_TEST_DB_URL=mysql://db:db@db/db
  - DRUPAL_TEST_WEBDRIVER_HOSTNAME=selenium-chrome
  - DRUPAL_TEST_WEBDRIVER_PORT=4444
  - DRUPAL_TEST_WEBDRIVER_PATH_PREFIX=/wd/hub
  - DRUPAL_TEST_WEBDRIVER_CHROME_ARGS=--disable-gpu --headless --no-sandbox --disable-dev-shm-usage
  - DRUPAL_TEST_CHROMEDRIVER_AUTOSTART=false
  - DRUPAL_NIGHTWATCH_SEARCH_DIRECTORY=../
  - DRUPAL_NIGHTWATCH_IGNORE_DIRECTORIES=node_modules,vendor,.*,sites/*/files,sites/*/private,sites/simpletest
  - DRUPAL_NIGHTWATCH_OUTPUT=reports/nightwatch
  # DTT
  - DTT_BASE_URL=http://web
  - DTT_MINK_DRIVER_ARGS=[\"chrome\", {\"browserName\":\"chrome\",\"goog:chromeOptions\":{\"w3c\":false,\"args\":[\"--disable-gpu\",\"--headless\", \"--no-sandbox\", \"--disable-dev-shm-usage\"]}}, \"http://selenium-chrome:4444/wd/hub\"]
