name: Build & deploy review site
on:
  push:
    branches:
      - kitten

jobs:
  review-site:
    name: Build & deploy review site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scaffolding
        uses: actions/checkout@v2
        with:
          repository: az-digital/az-quickstart-scaffolding
          path: az-quickstart-scaffolding

      - name: Setup PHP
        uses: shivammathur/setup-php@d2f58713aaf7809d0c4d11e827c9e9dbbc55b34e
        with:
          php-version: '7.4'

      - name: Build Arizona Quickstart
        run: |
          (
            cd az-quickstart-scaffolding
            composer install
          )

      - name: Set up SSH
        run: |
          echo foo
          mkdir ${HOME}/.ssh && chmod 700 ${HOME}/.ssh
          echo "Host *.drush.in\n    StrictHostKeyChecking no" > ${HOME}/.ssh/config
          echo "${{ secrets.PANTHEON_SSH_KEY }}" > ${HOME}/.ssh/id_rsa
          chmod 600 ${HOME}/.ssh/*

      - name: Install terminus
        run: |
          composer require pantheon-systems/terminus:^2
          echo "$(pwd)/vendor/bin" >> ${GITHUB_PATH}

      - name: Set up terminus
        run: |
          terminus -y auth:login --machine-token ${{ secrets.TERMINUS_TOKEN }}

      - name: Sync code to pantheon
        run: |
          terminus -y art
          pwd
          ls -al

      - name: Wipe existing site
        run: |
          terminus -y env:wipe ${{ secrets.DEMO_SITE_NAME }}.dev

      - name: Install site
        run: |
          echo terminus -y drush ${{ secrets.DEMO_SITE_NAME }}.dev -- \
          site-install az_quickstart install_configure_form.update_status_module='array(FALSE,FALSE)' \
          --account-name="azadmin" \
          --account-mail="noreply@email.arizona.edu" \
          --site-mail="noreply@email.arizona.edu" \
          --site-name="Kitten" \
          --yes
          # --verbose

      - name: Clear caches
        run: |
          terminus -y env:clear-cache ${{ secrets.DEMO_SITE_NAME }}.dev
