name: Test PR on Release Branch
on:
    pull_request:
      types:
        - opened
  #  workflow_dispatch:
  #   inputs:
  #     release_branch:
  #       description: The release branch to test this PR on
  #       required: true
  #       type: choice
  #       options: 
  #         - 2.1.x
  #         - 2.2.x

jobs:
  test-pr-on-branch:
    name: Test PR on Release Branch
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        release:
          - "2.1.x"
          - "2.2.x"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@d2f58713aaf7809d0c4d11e827c9e9dbbc55b34e
        with:
          php-version: '7.4'

      - name: Apply PR diff to release branch
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git checkout "${RELEASE_BRANCH}"
          AZ_TRIMMED_REF="${GITHUB_REF##*/}"
          echo "BRANCH BELOW"
          echo "${AZ_TRIMMED_REF}"
          git merge "${AZ_TRIMMED_REF}"
          composer install
        env:
          RELEASE_BRANCH: ${{ matrix.release }}
