name: Test PR on Release Branch
on: push
    # pull_request:
    #   types:
    #     - opened
    
  #  workflow_dispatch:
  #   inputs:
  #     release_branch:
  #       description: The release branch to test this PR on
  #       required: true
  #       type: choice
  #       options: 
  #         - 2.1.x
  #         - 2.2.x


jobs:
  test-pr-on-branch:
    name: Test PR on Release Branch
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        release:
          - "2.1.x"
          - "2.2.x"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: az_quickstart

      - name: Setup PHP
        uses: shivammathur/setup-php@d2f58713aaf7809d0c4d11e827c9e9dbbc55b34e
        with:
          php-version: '7.4'

      - name: Apply PR diff to release branch
        id: apply
        working-directory: ./az_quickstart
        run: |
          set -x
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git fetch
          git checkout "${{ matrix.release }}"
          curl https://patch-diff.githubusercontent.com/raw/az-digital/az_quickstart/pull/1459.patch | git apply --reject --whitespace=fix
          
      - name: Composer Install
        run: |
          # Clone scaffolding repo into ./app
          git clone --branch ${{ matrix.release }} https://github.com/az-digital/az-quickstart-scaffolding.git ./app
          # Update az-digital/az_quickstart dependency to reference local (patched) copy of Quickstart
          cd app
          composer config repositories.localqs path ${GITHUB_WORKSPACE}/az_quickstart
          composer require --no-update az-digital/az_quickstart:\*@dev
          composer install         
        if: steps.apply.outcome == 'success'
        
        env:
          RELEASE_BRANCH: ${{ matrix.release }}
