name: Test PR on Release Branch
on: push
assets:
  - test-credentials.sh
    # pull_request:
    #   types:
    #     - opened
    
  #  workflow_dispatch:
  #   inputs:
  #     release_branch:
  #       description: The release branch to test this PR on
  #       required: true
  #       type: choice
  #       options: 
  #         - 2.1.x
  #         - 2.2.x


jobs:
  test-pr-on-branch:
    name: Test PR on Release Branch
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        release:
          - "2.1.x"
          - "2.2.x"
          # - "issue/1491"
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: db
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      chromedriver:
        image: drupalci/webdriver-chromedriver:production
        ports:
          - 9515
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: az_quickstart

      - name: Setup PHP
        uses: shivammathur/setup-php@d2f58713aaf7809d0c4d11e827c9e9dbbc55b34e
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv

      - name: Apply PR diff to release branch
        id: apply
        working-directory: ./az_quickstart
        run: |
          set -x
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git fetch
          git checkout "${{ matrix.release }}"
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "${PR_NUMBER}"
          curl https://patch-diff.githubusercontent.com/raw/az-digital/az_quickstart/pull/1408.path | git apply --reject --whitespace=fix --allow-empty
          
          
      - name: Composer Install
        id: install
        #if: steps.apply.outcome == 'failure'
        run: |
          set -x
          # Clone scaffolding repo into ./app
          git clone --branch ${{ matrix.release }} https://github.com/az-digital/az-quickstart-scaffolding.git ./app
          # Update az-digital/az_quickstart dependency to reference local (patched) copy of Quickstart
          cd app
          composer config repositories.localqs path ${GITHUB_WORKSPACE}/az_quickstart
          composer require --no-update az-digital/az_quickstart:\*@dev
          composer install         
       
      - name: Install Drush
        run: php ./app/vendor/bin/drush site:install az_quickstart --account-pass=admin --db-url=mysql://root:@127.0.0.1:${{ job.services.mysql.ports[3306] }}/db --yes

      - name: PHP Unit Tests
        run: |
          ./app/vendor/bin/phpunit --configuration web/profiles/custom/az_quickstart/phpunit.xml.dist --bootstrap web/core/tests/bootstrap.php web/profiles/custom/az_quickstart

      # - name: PHP Unit Tests
      #   run: |
      #     set -x
      #     sudo mkdir -p /var/www/html/sites/simpletest
      #     sudo chown www-data:www-data -R /var/www/html/sites/simpletest
      #     sudo mkdir -p /var/www/html/sites/default/files/simpletest
      #     sudo chown www-data:www-data -R /var/www/html/sites/default/files/simpletest
      #     sudo CHROMEDRIVER_VERSION=LATEST_$(/usr/bin/google-chrome --product-version | cut -d . -f 1-3) npm install --no-progress --unsafe-perm --global chromedriver
      #     sudo apt-get install daemonize
      #     source $ASSET_DIR/test-credentials.sh
      #     # source ./app/test-credentials.sh
      #     export SIMPLETEST_BASE_URL="http://localhost"
      #     export SIMPLETEST_DB="mysql://${TEST_DATABASE_USER}:${TEST_DATABASE_PASS}@localhost/${TEST_DATABASE_NAME}"
      #     export MINK_DRIVER_ARGS_WEBDRIVER='["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--disable-dev-shm-usage","--headless","--no-sandbox"]}}, "http://localhost:9515"]'
      #     daemonize /usr/local/bin/chromedriver --log-path=/tmp/chromedriver.log --verbose --whitelisted-ips="127.0.0.1"
      #     ls
      #     cd az_quickstart
      #     export RUN_TESTS_CONCURRENCY=10
      #     mysqladmin create ${TEST_DATABASE_NAME}
      #     sudo -u www-data -E find $SRC_DIR/az-quickstart-scaffolding/web/profiles/custom/az_quickstart/ -name "*Test.php" | sudo -u www-data -E $SRC_DIR/az-quickstart-scaffolding/vendor/bin/fastest -p 10 -vvv "$SRC_DIR/az-quickstart-scaffolding/vendor/bin/phpunit {} --colors="always" --verbose --do-not-cache-result;"
