<?php

/**
 * @file
 * AZ Zoom module.
 */

/**
 * Implements hook_theme().
 */
function az_zoom_theme() {
  return [
    'az_zoom' => [
      'variables' => [
        'images' => NULL,
      ],
      'template' => 'az-zoom',
    ],
  ];
}

/**
 * Implements hook_preprocess_az_zoom().
 */
function template_preprocess_az_zoom(&$variables) {
  $variables['#attached']['library'][] = 'az_zoom/drupal';
}
